# Genome Preprocessing and Dataset Construction

This notebook prepares the validated *Staphylococcus aureus* genome sequences
for sequence-based ciprofloxacin resistance prediction.

## Workflow

1. Load the genome retrieval manifest.
2. Perform final genome-level data quality checks.
3. Create genome-level train, validation, and test splits.
4. Prevent isolate-level leakage between splits.
5. Optionally evaluate genome relatedness using Mash/MinHash.
6. Generate fixed-length sequence windows independently within each split.
7. Track genomic coordinates and sequence quality for every window.
8. Convert sequence windows into one-hot encoded representations.
9. Prepare the resulting data for CNN training.

## Important Data-Splitting Principle

Genome-level splitting is performed **before** window generation.

Windows from the same genome must never appear across different dataset splits.
This prevents information leakage between training, validation, and test sets.

## Step 1 — Load Final Genome Manifest

The genome retrieval manifest links each phenotype-labeled genome to its
BV-BRC availability and local FASTA sequence.

In [1]:
import pandas as pd
from pathlib import Path

# Load final genome retrieval manifest

manifest_path = next(
    Path("/kaggle/input").rglob("genome_retrieval_manifest.csv")
)

manifest_df = pd.read_csv(
    manifest_path,
    dtype={"Genome ID": str}
)

print("Manifest shape:", manifest_df.shape)

print("\nColumns:")
print(manifest_df.columns.tolist())

print("\nFASTA availability:")
print(
    manifest_df["FASTA Available"].value_counts()
)

Manifest shape: (1205, 5)

Columns:
['Genome ID', 'Phenotype', 'Label', 'Metadata Available', 'FASTA Available']

FASTA availability:
FASTA Available
True     1138
False      67
Name: count, dtype: int64

In [2]:
from pathlib import Path
import torch

# 1. Check GPU availability
print("GPU available:", torch.cuda.is_available())

if torch.cuda.is_available():
    print("GPU:", torch.cuda.get_device_name(0))

# 2. List attached datasets
print("\nAttached datasets:")
input_dir = Path("/kaggle/input")

for path in input_dir.iterdir():
    print(path)

# 3. Locate the genome, processed, and raw data folders automatically
print("\nSearching for data folders:")

genome_dirs = list(input_dir.rglob("genomes"))
processed_dirs = list(input_dir.rglob("processed"))
raw_dirs = list(input_dir.rglob("raw"))

for name, folders in [
    ("genomes", genome_dirs),
    ("processed", processed_dirs),
    ("raw", raw_dirs),
]:
    print(f"\n{name} folders:")
    for folder in folders:
        if folder.is_dir():
            print(folder)

# 4. Verify genome files
if genome_dirs and genome_dirs[0].is_dir():
    genome_dir = genome_dirs[0]
    fasta_files = list(genome_dir.glob("*.fna"))

    print("\nGenome folder exists:", genome_dir.exists())
    print("Genome folder path:", genome_dir)
    print("FASTA files found:", len(fasta_files))
else:
    print("\nGenome folder was not found.")

GPU available: True
GPU: Tesla T4

Attached datasets:
/kaggle/input/datasets

Searching for data folders:

genomes folders:
/kaggle/input/datasets/prajaktananda1905/amr-data/data/genomes

processed folders:
/kaggle/input/datasets/prajaktananda1905/amr-data/data/processed

raw folders:
/kaggle/input/datasets/prajaktananda1905/amr-data/data/raw

Genome folder exists: True
Genome folder path: /kaggle/input/datasets/prajaktananda1905/amr-data/data/genomes
FASTA files found: 1138

In [3]:
from pathlib import Path

for path in Path("/kaggle/input").rglob("*"):
    if path.is_dir() and path.name in {"genomes", "processed", "raw"}:
        print(path)

/kaggle/input/datasets/prajaktananda1905/amr-data/data/genomes
/kaggle/input/datasets/prajaktananda1905/amr-data/data/processed
/kaggle/input/datasets/prajaktananda1905/amr-data/data/raw

## Step 2 — Define the Modeling Cohort

The modeling cohort contains only genomes with successfully retrieved FASTA
sequences.

The 67 genomes unavailable from BV-BRC remain documented in the retrieval
manifest but are excluded from sequence-based modeling.

In [4]:
# Select genomes with successfully retrieved FASTA files

model_df = manifest_df[
    manifest_df["FASTA Available"] == True
].copy()

print("Modeling genomes:", len(model_df))

print("\nLabel distribution:")
print(model_df["Label"].value_counts())

print("\nPhenotype distribution:")
print(model_df["Phenotype"].value_counts())

print("\nUnique Genome IDs:", model_df["Genome ID"].nunique())

Modeling genomes: 1138

Label distribution:
Label
0    664
1    474
Name: count, dtype: int64

Phenotype distribution:
Phenotype
('Susceptible',)    664
('Resistant',)      474
Name: count, dtype: int64

Unique Genome IDs: 1138

## Step 3 — Clean Phenotype Labels

The phenotype column is normalized to plain string labels so that the dataset
contains the intended categorical values:

- Susceptible
- Resistant

The binary `Label` column remains unchanged:
- 0 = Susceptible
- 1 = Resistant

In [5]:
# Normalize phenotype labels

model_df["Phenotype"] = (
    model_df["Phenotype"]
    .astype(str)
    .str.strip("()', ")
)

print("Phenotype distribution:")
print(model_df["Phenotype"].value_counts())

print("\nUnique phenotype values:")
print(model_df["Phenotype"].unique())

Phenotype distribution:
Phenotype
Susceptible    664
Resistant      474
Name: count, dtype: int64

Unique phenotype values:
['Susceptible' 'Resistant']

## Step 4 — Genome-Level Train/Validation/Test Split

The modeling cohort is divided at the genome level using a stratified split:

- 70% training
- 15% validation
- 15% testing

Stratification preserves the Resistant/Susceptible proportion across splits.

The split is performed before genome window generation to prevent windows
originating from the same genome from appearing across different datasets.

In [6]:
from sklearn.model_selection import train_test_split

# First split: 70% training, 30% temporary
train_df, temp_df = train_test_split(
    model_df,
    test_size=0.30,
    stratify=model_df["Label"],
    random_state=42
)

# Second split: divide the temporary 30% equally
# → 15% validation, 15% test
val_df, test_df = train_test_split(
    temp_df,
    test_size=0.50,
    stratify=temp_df["Label"],
    random_state=42
)

print("Train genomes:", len(train_df))
print("Validation genomes:", len(val_df))
print("Test genomes:", len(test_df))

print("\nTrain label distribution:")
print(train_df["Label"].value_counts())

print("\nValidation label distribution:")
print(val_df["Label"].value_counts())

print("\nTest label distribution:")
print(test_df["Label"].value_counts())

Train genomes: 796
Validation genomes: 171
Test genomes: 171

Train label distribution:
Label
0    464
1    332
Name: count, dtype: int64

Validation label distribution:
Label
0    100
1     71
Name: count, dtype: int64

Test label distribution:
Label
0    100
1     71
Name: count, dtype: int64

## Step 5 — Verify Genome-Level Split Integrity

The train, validation, and test sets must contain completely disjoint Genome IDs.

This prevents genomic windows originating from the same isolate from appearing
in multiple dataset partitions and causing data leakage.

In [7]:
# Verify that Genome IDs are completely disjoint

train_ids = set(train_df["Genome ID"])
val_ids = set(val_df["Genome ID"])
test_ids = set(test_df["Genome ID"])

train_val_overlap = train_ids & val_ids
train_test_overlap = train_ids & test_ids
val_test_overlap = val_ids & test_ids

print("Train ∩ Validation:", len(train_val_overlap))
print("Train ∩ Test:", len(train_test_overlap))
print("Validation ∩ Test:", len(val_test_overlap))

print("\nTotal unique Genome IDs across all splits:",
      len(train_ids | val_ids | test_ids))

print("Expected unique Genome IDs:", len(model_df))

if not train_val_overlap and not train_test_overlap and not val_test_overlap:
    print("\n✓ No genome-level leakage detected.")
else:
    print("\n✗ Genome overlap detected.")

Train ∩ Validation: 0
Train ∩ Test: 0
Validation ∩ Test: 0

Total unique Genome IDs across all splits: 1138
Expected unique Genome IDs: 1138

✓ No genome-level leakage detected.

## Step 6 — Define Genome Windowing

Each genome is processed contig-by-contig rather than concatenated into a
single artificial sequence.

Each contig is divided into overlapping windows using:

- Window size: 500 bp
- Stride: 250 bp

For every generated window, we retain:

- Genome ID
- Contig ID
- Start coordinate
- End coordinate
- Strand
- Sequence
- Fraction of ambiguous bases (N)

Windows are generated only after the genome-level train/validation/test split,
ensuring that windows from the same isolate cannot cross dataset boundaries.

In [8]:
# Windowing configuration

WINDOW_SIZE = 500
STRIDE = 250

print("Window size:", WINDOW_SIZE)
print("Stride:", STRIDE)

Window size: 500
Stride: 250

## Step 7 — Parse Genome FASTA into Contigs

Genome FASTA files may contain multiple contigs. Each contig is treated as an
independent nucleotide sequence.

We parse the FASTA file into a dictionary mapping each contig identifier to
its nucleotide sequence.

Contigs are never concatenated across boundaries.

In [9]:
from pathlib import Path

def parse_fasta(fasta_path):
    """
    Parse a FASTA file into a dictionary:
    {contig_id: nucleotide_sequence}
    """
    contigs = {}
    current_id = None
    sequence_parts = []

    with open(fasta_path, "r") as f:
        for line in f:
            line = line.strip()

            if not line:
                continue

            if line.startswith(">"):
                if current_id is not None:
                    contigs[current_id] = "".join(sequence_parts)

                current_id = line[1:].split()[0]
                sequence_parts = []

            else:
                sequence_parts.append(line.upper())

        if current_id is not None:
            contigs[current_id] = "".join(sequence_parts)

    return contigs

In [10]:
from pathlib import Path

# Automatically locate the genome folder in the attached Kaggle dataset
input_dir = Path("/kaggle/input")
genome_matches = list(input_dir.rglob("genomes"))

genome_dirs = [
    path for path in genome_matches
    if path.is_dir() and path.parent.name == "data"
]

if not genome_dirs:
    raise FileNotFoundError("Could not find the genomes folder in Kaggle input.")

genome_dir = genome_dirs[0]

print("Genome directory:", genome_dir)
print("Directory exists:", genome_dir.exists())
print("FASTA files found:", len(list(genome_dir.glob("*.fna"))))

Genome directory: /kaggle/input/datasets/prajaktananda1905/amr-data/data/genomes
Directory exists: True
FASTA files found: 1138

In [11]:
# Test FASTA parsing on the representative genome

test_genome_id = "1280.15865"
test_fasta_path = genome_dir / f"{test_genome_id}.fna"

test_contigs = parse_fasta(test_fasta_path)

print("Genome ID:", test_genome_id)
print("Number of contigs:", len(test_contigs))

print("\nFirst 5 contigs:")
for contig_id, sequence in list(test_contigs.items())[:5]:
    print(contig_id, "—", len(sequence), "bp")

Genome ID: 1280.15865
Number of contigs: 26

First 5 contigs:
accn|LKNK01000018 — 87177 bp
accn|LKNK01000003 — 198837 bp
accn|LKNK01000016 — 83819 bp
accn|LKNK01000010 — 130579 bp
accn|LKNK01000006 — 24070 bp

## Step 8 — Define Genome Windowing Function

Each genome is processed contig-by-contig.

For each contig, overlapping windows are generated using:
- Window size: 500 bp
- Stride: 250 bp

Windows are never generated across contig boundaries.

Each window retains:
- Genome ID
- Contig ID
- Start coordinate
- End coordinate
- Strand
- Sequence
- Fraction of ambiguous bases (N)

Window generation occurs only after genome-level dataset splitting,
preventing windows from the same isolate from appearing across different
dataset partitions.

In [12]:
# Windowing configuration

WINDOW_SIZE = 500
STRIDE = 250

print("Window size:", WINDOW_SIZE)
print("Stride:", STRIDE)

Window size: 500
Stride: 250

In [13]:
def generate_windows(sequence, window_size=500, stride=250):
    """
    Generate overlapping windows from a single contig sequence.

    Windows are generated only within the contig.
    The final incomplete window is discarded.
    """
    windows = []

    for start in range(0, len(sequence) - window_size + 1, stride):
        end = start + window_size
        window_sequence = sequence[start:end]

        n_fraction = window_sequence.upper().count("N") / window_size

        windows.append({
            "Start": start,
            "End": end,
            "Sequence": window_sequence,
            "N_fraction": n_fraction
        })

    return windows

In [14]:
# Test window generation on one contig

first_contig_id, first_contig_sequence = next(iter(test_contigs.items()))

test_windows = generate_windows(
    first_contig_sequence,
    WINDOW_SIZE,
    STRIDE
)

print("Contig ID:", first_contig_id)
print("Contig length:", len(first_contig_sequence), "bp")
print("Number of windows:", len(test_windows))

print("\nFirst window:")
print(test_windows[0])

Contig ID: accn|LKNK01000018
Contig length: 87177 bp
Number of windows: 347

First window:
{'Start': 0, 'End': 500, 'Sequence': 'TCTTACTGCTGTTTTTTTAGGGATTTATGTCCCAGCCTCTTTTTGGTTTTAATTTTACAATAATTGCTTAGTATCTTTTAAATCAAATGTGCAATTGTTAATATAGCTCTATATTAGAGTGTTTTGGATGAAACATTTGCTATGATAAGGTAAAATTAAATTAAGAAAGTGCTTTAATGCTTTAACTGTATAAATCATTTAAATAGTTTTGCTACAACGAATATGTTATTATAAGTTACCAAAATATTTTAGAGAAAGAAATCAAACAAATAAATTGTATTTTGTTTGATGCTTTAATACAATGTGGATACTATTCATCGACTGTAAGGAGTGAGATGATATGAGAATAGAACGAGTAGATGATACAACTGTAAAATTGTTTATAACATATAGCGATATCGAGGCCCGTGGATTTAGTCGTGAAGATTTATGGACAAATCGCAAACGTGGCGAAGAATTCTTTTGGTCAATGATGGATGAAATTAACGAAGAAGAAGATT', 'N_fraction': 0.0}

In [15]:
# Inspect the first few window coordinates

for window in test_windows[:5]:
    print(
        "Start:", window["Start"],
        "| End:", window["End"],
        "| Length:", len(window["Sequence"]),
        "| N fraction:", window["N_fraction"]
    )

Start: 0 | End: 500 | Length: 500 | N fraction: 0.0
Start: 250 | End: 750 | Length: 500 | N fraction: 0.0
Start: 500 | End: 1000 | Length: 500 | N fraction: 0.0
Start: 750 | End: 1250 | Length: 500 | N fraction: 0.0
Start: 1000 | End: 1500 | Length: 500 | N fraction: 0.0

In [17]:
# Test windowing on several contigs

# Test windowing on several contigs

test_contigs_sample = list(test_contigs)[:5]

for i, item in enumerate(test_contigs_sample):
    # Support either (contig_id, sequence) tuples or plain sequences
    if isinstance(item, tuple) and len(item) == 2:
        contig_id, sequence = item
    else:
        contig_id = f"contig_{i + 1}"
        sequence = item

    windows = generate_windows(
        sequence,
        window_size=WINDOW_SIZE,
        stride=STRIDE
    )

    print(
        contig_id,
        "| Contig length:", len(sequence),
        "| Windows:", len(windows)
    )

contig_1 | Contig length: 17 | Windows: 0
contig_2 | Contig length: 17 | Windows: 0
contig_3 | Contig length: 17 | Windows: 0
contig_4 | Contig length: 17 | Windows: 0
contig_5 | Contig length: 17 | Windows: 0

## Step 12 — Estimate Total Genome Windows

Before generating the complete window-level dataset, we first estimate the
number of windows that will be produced from the modeling cohort.

This provides an approximate dataset size and helps determine whether the
window-level data can be safely constructed in memory or should be processed
in batches.

For each genome:

1. Load the corresponding FASTA file.
2. Parse the genome into individual contigs.
3. Generate windows independently within each contig.
4. Count the resulting windows.
5. Sum the counts across all genomes in the modeling cohort.

The current windowing configuration is:

- Window size: **500 bp**
- Stride: **250 bp**
- Contigs are processed independently.
- Windows are generated only from genomes belonging to the modeling cohort.

No window-level data is saved at this stage; this step only estimates the
total number of windows that will be generated.

In [18]:
# Estimate total number of windows in the modeling cohort

total_windows = 0
genomes_with_files = 0

for genome_id in model_df["Genome ID"]:
    fasta_path = genome_dir / f"{genome_id}.fna"

    if not fasta_path.exists():
        continue

    contigs = parse_fasta(fasta_path)

    for sequence in contigs.values():
        total_windows += len(
            generate_windows(
                sequence,
                window_size=WINDOW_SIZE,
                stride=STRIDE
            )
        )

    genomes_with_files += 1

print("Genomes available:", genomes_with_files)
print("Estimated total windows:", total_windows)

Genomes available: 1138
Estimated total windows: 12701599

## Step 13 — Estimate Windows Per Dataset Split

The modeling cohort has already been divided at the genome level into
training, validation, and test sets.

Before constructing the complete window-level dataset, we estimate the
number of windows produced by each split.

This step is important because the number of windows can be very large,
especially when using overlapping 500 bp windows with a 250 bp stride.

The estimate will guide the subsequent dataset-construction strategy and
help avoid loading the complete window-level dataset into memory at once.

Windows remain associated with their source genome and are generated only
after the genome-level split, preserving the separation between training,
validation, and test genomes.

In [19]:
# Estimate the number of windows in each dataset split

def estimate_split_windows(split_df):
    total_windows = 0
    genomes_processed = 0

    for genome_id in split_df["Genome ID"]:
        fasta_path = genome_dir / f"{genome_id}.fna"

        if not fasta_path.exists():
            continue

        contigs = parse_fasta(fasta_path)

        for sequence in contigs.values():
            total_windows += len(
                generate_windows(
                    sequence,
                    window_size=WINDOW_SIZE,
                    stride=STRIDE
                )
            )

        genomes_processed += 1

    return genomes_processed, total_windows


train_genomes, train_windows = estimate_split_windows(train_df)
val_genomes, val_windows = estimate_split_windows(val_df)
test_genomes, test_windows = estimate_split_windows(test_df)

print("Training genomes:", train_genomes)
print("Training windows:", train_windows)

print("\nValidation genomes:", val_genomes)
print("Validation windows:", val_windows)

print("\nTest genomes:", test_genomes)
print("Test windows:", test_windows)

print("\nTotal windows:", train_windows + val_windows + test_windows)

Training genomes: 796
Training windows: 8878455

Validation genomes: 171
Validation windows: 1912079

Test genomes: 171
Test windows: 1911065

Total windows: 12701599

## Step 14 — Define Genome-Level Window Processing

Each genome is treated as one multiple-instance learning (MIL) bag.

The genome is first parsed into its individual contigs, and windows are
generated independently within each contig using the configured window size
and stride.

Each generated window retains its genomic provenance:

- Genome ID
- Phenotype
- Binary label
- Contig ID
- Start coordinate
- End coordinate
- Strand
- N fraction
- Sequence

The windows are therefore treated as instances belonging to a particular
genome rather than as independent training examples.

This distinction is essential because the final prediction target is the
genome-level antimicrobial-resistance phenotype.

In [26]:
def process_genome(genome_id):
    """
    Process one genome into its window-level MIL instances.

    Each genome remains a single MIL bag, while individual windows
    retain their genomic coordinates and source information.
    """

    # Locate FASTA file
    fasta_path = genome_dir / f"{genome_id}.fna"

    if not fasta_path.exists():
        raise FileNotFoundError(
            f"FASTA file not found for Genome ID: {genome_id}"
        )

    # Get genome-level label information
    genome_row = model_df[
        model_df["Genome ID"] == genome_id
    ]

    if len(genome_row) != 1:
        raise ValueError(
            f"Expected exactly one phenotype record for {genome_id}, "
            f"found {len(genome_row)}"
        )

    phenotype = genome_row.iloc[0]["Phenotype"]
    label = int(genome_row.iloc[0]["Label"])

    # Parse genome into contigs
    contigs = parse_fasta(fasta_path)

    windows = []

    # Generate windows independently for each contig
    for contig_id, sequence in contigs.items():

        contig_windows = generate_windows(
            sequence,
            window_size=WINDOW_SIZE,
            stride=STRIDE
        )

        for window in contig_windows:

            windows.append({
                "Genome ID": genome_id,
                "Phenotype": phenotype,
                "Label": label,
                "Contig ID": contig_id,
                "Start": window["Start"],
                "End": window["End"],
                "Strand": "+",
                "Sequence": window["Sequence"],
                "N_fraction": window["N_fraction"]
            })

    return windows

In [27]:
test_genome_id = "1280.15865"

test_genome_windows = process_genome(test_genome_id)

print("Genome ID:", test_genome_id)
print("Total windows:", len(test_genome_windows))

print("\nFirst window:")
print(test_genome_windows[0])

print("\nLast window:")
print(test_genome_windows[-1])

Genome ID: 1280.15865
Total windows: 10885

First window:
{'Genome ID': '1280.15865', 'Phenotype': 'Susceptible', 'Label': 0, 'Contig ID': 'accn|LKNK01000018', 'Start': 0, 'End': 500, 'Strand': '+', 'Sequence': 'TCTTACTGCTGTTTTTTTAGGGATTTATGTCCCAGCCTCTTTTTGGTTTTAATTTTACAATAATTGCTTAGTATCTTTTAAATCAAATGTGCAATTGTTAATATAGCTCTATATTAGAGTGTTTTGGATGAAACATTTGCTATGATAAGGTAAAATTAAATTAAGAAAGTGCTTTAATGCTTTAACTGTATAAATCATTTAAATAGTTTTGCTACAACGAATATGTTATTATAAGTTACCAAAATATTTTAGAGAAAGAAATCAAACAAATAAATTGTATTTTGTTTGATGCTTTAATACAATGTGGATACTATTCATCGACTGTAAGGAGTGAGATGATATGAGAATAGAACGAGTAGATGATACAACTGTAAAATTGTTTATAACATATAGCGATATCGAGGCCCGTGGATTTAGTCGTGAAGATTTATGGACAAATCGCAAACGTGGCGAAGAATTCTTTTGGTCAATGATGGATGAAATTAACGAAGAAGAAGATT', 'N_fraction': 0.0}

Last window:
{'Genome ID': '1280.15865', 'Phenotype': 'Susceptible', 'Label': 0, 'Contig ID': 'accn|LKNK01000023', 'Start': 17750, 'End': 18250, 'Strand': '+', 'Sequence': 'GTCATGATTGGTAGAGGCATTTTCCATAATCCATTCGCTTTTGAAAAAGAACCACGCGAACACACAAGCAAAGAACTATTAGATTTGTTGAGATTGCATTTATCATTGTTTAACAAATATGAAAAAGATGAAATACGACAATTCAAGAGTTTGCGTAGATTCTTTAAAATCTATGTGCGTGGCATAAGAGGCGCTAGCGAACTTCGCCATCAGTTGATGAATACACAATCAATTGCAGAAGCACGAGCACTACTAGATGAATTTGAAGCCCAAATGGACGAAGACGTTAAAATAGAATTATAGTATGAGAAATAAAGGAAAGGAGGAATTTAAGTTTCCTCCTTTTTACTCGTTCTAATTCATTTTCTTTACCTACTTCATAATATCTTTTAACTGTTCTTGAGTCACAATCATTTGATCTCCTATCAAAGGTTGAGTTAGGAAATGATTATATAATTTTAAAAAGAAAAAATATAGGAAAAACAACATTTTCATTTCGT', 'N_fraction': 0.0}

## Step 16 — Validate Window Integrity

The generated windows are validated before being used for model training.

The validation checks:

- Every window has the expected length of 500 bp.
- Window coordinates correspond to the sequence length.
- Only valid nucleotide characters (`A`, `C`, `G`, `T`, `N`) are present.
- The reported `N_fraction` agrees with the number of ambiguous bases.
- Windows do not extend beyond their source contig boundaries.

These checks ensure that the window-generation process produces valid,
well-defined genomic instances before numerical sequence representation and
model training.

In [28]:
# Validate window integrity for the test genome

valid_bases = set("ACGTN")

invalid_length = []
invalid_coordinates = []
invalid_bases = []
invalid_n_fraction = []

for window in test_genome_windows:

    sequence = window["Sequence"]
    start = window["Start"]
    end = window["End"]

    # Check sequence length
    if len(sequence) != WINDOW_SIZE:
        invalid_length.append(window)

    # Check coordinate length
    if end - start != WINDOW_SIZE:
        invalid_coordinates.append(window)

    # Check nucleotide characters
    if not set(sequence).issubset(valid_bases):
        invalid_bases.append(window)

    # Check N fraction
    expected_n_fraction = sequence.count("N") / len(sequence)

    if abs(window["N_fraction"] - expected_n_fraction) > 1e-9:
        invalid_n_fraction.append(window)


print("Total windows:", len(test_genome_windows))

print("Invalid sequence lengths:", len(invalid_length))
print("Invalid coordinates:", len(invalid_coordinates))
print("Invalid nucleotide characters:", len(invalid_bases))
print("Incorrect N fractions:", len(invalid_n_fraction))

if not any([
    invalid_length,
    invalid_coordinates,
    invalid_bases,
    invalid_n_fraction
]):
    print("\n✓ Window integrity validation passed.")
else:
    print("\n✗ Window integrity problems detected.")

Total windows: 10885
Invalid sequence lengths: 0
Invalid coordinates: 0
Invalid nucleotide characters: 0
Incorrect N fractions: 0

✓ Window integrity validation passed.

## Step 17 — Validate Window Coverage

The windowing procedure is further validated by comparing the genomic
sequence covered by the generated windows with the source contig lengths.

Because the windows use a 500 bp size and 250 bp stride, overlapping windows
are expected. Therefore, this check verifies the number and coordinate range
of windows rather than requiring every base to occur only once.

This confirms that windows remain within their respective contigs and that
the window-generation procedure is consistent across contigs.

In [30]:

# Validate window coverage for the test genome

coverage_errors = []

# Normalize test_contigs into (contig_id, sequence) pairs
if isinstance(test_contigs, dict):
    contig_items = list(test_contigs.items())
else:
    contig_items = []

    for i, item in enumerate(test_contigs):
        if isinstance(item, dict):
            contig_id = item.get("Contig ID", item.get("contig_id", str(i)))
            sequence = item.get("Sequence", item.get("sequence"))

        elif isinstance(item, (tuple, list)):
            # The sequence is expected to be the final item.
            if len(item) < 2:
                coverage_errors.append((str(i), "Invalid contig record"))
                continue

            contig_id = item[0]
            sequence = item[-1]

        else:
            # A plain sequence string
            contig_id = str(i)
            sequence = item

        if sequence is None:
            coverage_errors.append((str(contig_id), "Missing sequence"))
            continue

        contig_items.append((contig_id, sequence))

for contig_id, sequence in contig_items:
    contig_length = len(sequence)

    contig_windows = [
        window for window in test_genome_windows
        if window["Contig ID"] == contig_id
    ]

    if not contig_windows:
        coverage_errors.append((contig_id, "No windows generated"))
        continue

    # Sort windows by start position before checking coverage
    contig_windows.sort(key=lambda window: window["Start"])

    if contig_windows[0]["Start"] != 0:
        coverage_errors.append(
            (contig_id, "First window does not start at 0")
        )

    for window in contig_windows:
        if window["End"] > contig_length:
            coverage_errors.append(
                (contig_id, "Window extends beyond contig")
            )
            break

    if contig_windows[-1]["End"] > contig_length:
        coverage_errors.append(
            (contig_id, "Last window exceeds contig length")
        )

print("Total contigs:", len(contig_items))
print("Contigs with coverage errors:", len(coverage_errors))

if not coverage_errors:
    print("\nWindow coverage validation passed.")
else:
    print("\nCoverage problems detected.")
    print(coverage_errors[:10])

Total contigs: 26
Contigs with coverage errors: 0

Window coverage validation passed.

## Step 18 — Define One-Hot Sequence Encoding

Each 500 bp DNA window is converted into a numerical representation
suitable for the CNN.

Each nucleotide is represented using a four-dimensional one-hot vector:

- A → [1, 0, 0, 0]
- C → [0, 1, 0, 0]
- G → [0, 0, 1, 0]
- T → [0, 0, 0, 1]

Ambiguous nucleotide `N` is represented as:

- N → [0, 0, 0, 0]

The resulting representation for a 500 bp window has shape:

    (500, 4)

This representation preserves the nucleotide sequence while allowing the
CNN to learn local sequence patterns.

In [31]:
# Define one-hot encoding for DNA sequences

import numpy as np

BASE_TO_VECTOR = {
    "A": [1, 0, 0, 0],
    "C": [0, 1, 0, 0],
    "G": [0, 0, 1, 0],
    "T": [0, 0, 0, 1],
    "N": [0, 0, 0, 0]
}


def one_hot_encode(sequence):
    """
    Convert a DNA sequence into a one-hot encoded NumPy array.

    Output shape:
        (sequence_length, 4)
    """

    sequence = sequence.upper()

    encoded = np.array(
        [BASE_TO_VECTOR[base] for base in sequence],
        dtype=np.float32
    )

    return encoded

## Step 19 — Test One-Hot Encoding

A representative 500 bp window is encoded to verify that the one-hot
representation has the expected dimensions and nucleotide mappings.

The test checks:

- Output shape is `(500, 4)`
- Each standard nucleotide maps to exactly one active channel
- Ambiguous `N` bases are encoded as `[0, 0, 0, 0]`

In [33]:
# Test one-hot encoding on the first genome window

test_sequence = test_genome_windows[0]["Sequence"]

encoded_test = one_hot_encode(test_sequence)

print("Original sequence length:", len(test_sequence))
print("Encoded shape:", encoded_test.shape)

print("\nFirst 10 bases:")
print(test_sequence[:10])

print("\nFirst 10 encoded rows:")
print(encoded_test[:10])

print("\nUnique encoded vectors:")
print(np.unique(encoded_test, axis=0))

if encoded_test.shape == (500, 4):
    print("\n✓ One-hot encoding shape is correct.")
else:
    print("\n✗ Unexpected encoding shape.")

Original sequence length: 500
Encoded shape: (500, 4)

First 10 bases:
TCTTACTGCT

First 10 encoded rows:
[[0. 0. 0. 1.]
 [0. 1. 0. 0.]
 [0. 0. 0. 1.]
 [0. 0. 0. 1.]
 [1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 0. 1.]
 [0. 0. 1. 0.]
 [0. 1. 0. 0.]
 [0. 0. 0. 1.]]

Unique encoded vectors:
[[0. 0. 0. 1.]
 [0. 0. 1. 0.]
 [0. 1. 0. 0.]
 [1. 0. 0. 0.]]

✓ One-hot encoding shape is correct.

## Step 20 — Validate Ambiguous Base Encoding

Ambiguous nucleotide bases are represented by `N`.

To avoid assigning an arbitrary nucleotide identity to an ambiguous base,
`N` is encoded as:

    N → [0, 0, 0, 0]

This test explicitly verifies that the encoder handles ambiguous bases
according to the defined representation.

In [34]:
# Test ambiguous N-base encoding

n_test_sequence = "ACGTN"

n_encoded = one_hot_encode(n_test_sequence)

print("Test sequence:", n_test_sequence)
print("\nEncoded representation:")
print(n_encoded)

print("\nEncoding of N:")
print(n_encoded[4])

if np.array_equal(n_encoded[4], [0, 0, 0, 0]):
    print("\n✓ N is correctly encoded as [0, 0, 0, 0].")
else:
    print("\n✗ N encoding is incorrect.")

Test sequence: ACGTN

Encoded representation:
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]
 [0. 0. 0. 0.]]

Encoding of N:
[0. 0. 0. 0.]

✓ N is correctly encoded as [0, 0, 0, 0].

## Step 21 — Validate Encoding Across the Test Genome

The one-hot encoder is tested across all windows generated from the
representative genome.

This verifies that:

- Every window produces the expected `(500, 4)` representation.
- All encoded values are valid binary values.
- No unexpected nucleotide encoding occurs.

The complete dataset will not be materialized in memory at this stage.
This test is restricted to one genome before scaling to the full cohort.

In [35]:
# Validate one-hot encoding across all windows of the test genome

encoded_windows = []

for window in test_genome_windows:
    encoded = one_hot_encode(window["Sequence"])
    encoded_windows.append(encoded)

# Convert to a single test array
encoded_windows_array = np.stack(encoded_windows)

print("Number of windows:", len(encoded_windows_array))
print("Encoded array shape:", encoded_windows_array.shape)

print("Minimum value:", encoded_windows_array.min())
print("Maximum value:", encoded_windows_array.max())

# Validate dimensions and values
shape_valid = encoded_windows_array.shape == (len(test_genome_windows), 500, 4)
values_valid = np.all(
    np.isin(encoded_windows_array, [0.0, 1.0])
)

if shape_valid and values_valid:
    print("\n✓ Genome-wide one-hot encoding validation passed.")
else:
    print("\n✗ Encoding validation failed.")

Number of windows: 10885
Encoded array shape: (10885, 500, 4)
Minimum value: 0.0
Maximum value: 1.0

✓ Genome-wide one-hot encoding validation passed.

## Step 22 — Define Streaming Window Batches

The complete genome cohort contains millions of overlapping windows.
Therefore, all windows will not be one-hot encoded and stored simultaneously.

Instead, windows from each genome are processed in manageable batches.

For each genome:

1. Generate its windows.
2. Divide the windows into batches.
3. One-hot encode each batch.
4. Process the batch through the CNN.
5. Retain the resulting window embeddings for genome-level aggregation.

This preserves the multiple-instance learning structure while controlling
memory usage during model training.

In [36]:
# Window batch size
WINDOW_BATCH_SIZE = 128


def generate_window_batches(windows, batch_size=WINDOW_BATCH_SIZE):
    """
    Yield one-hot encoded batches of genome windows.

    Each batch has shape:
        (batch_size, 500, 4)

    The final batch may contain fewer than batch_size windows.
    """
    
    for start in range(0, len(windows), batch_size):
        batch_windows = windows[start:start + batch_size]

        batch_encoded = np.stack([
            one_hot_encode(window["Sequence"])
            for window in batch_windows
        ])

        yield batch_encoded

In [37]:
print("Type of test_windows:", type(test_windows))
print("Value of test_windows:", test_windows if isinstance(test_windows, int) else "not an integer")

print("\nType of test_genome_windows:", type(test_genome_windows))
print("Type of test_windows:", type(test_windows))

Type of test_windows: <class 'int'>
Value of test_windows: 1911065

Type of test_genome_windows: <class 'list'>
Type of test_windows: <class 'int'>

In [38]:
# Use the actual window list from the representative genome
representative_windows = test_genome_windows

print("Type:", type(representative_windows))
print("Number of windows:", len(representative_windows))

Type: <class 'list'>
Number of windows: 10885

In [39]:
# Test streaming batches on the representative genome

batch_generator = generate_window_batches(
    representative_windows,
    batch_size=WINDOW_BATCH_SIZE
)

batch_count = 0
total_windows = 0

for batch in batch_generator:
    batch_count += 1
    total_windows += batch.shape[0]

    if batch_count <= 3:
        print(f"Batch {batch_count}:", batch.shape)

print("\nTotal batches:", batch_count)
print("Total windows processed:", total_windows)
print("Expected windows:", len(representative_windows))

if total_windows == len(representative_windows):
    print("\n✓ All windows were processed exactly once.")
else:
    print("\n✗ Window count mismatch.")

Batch 1: (128, 500, 4)
Batch 2: (128, 500, 4)
Batch 3: (128, 500, 4)

Total batches: 86
Total windows processed: 10885
Expected windows: 10885

✓ All windows were processed exactly once.

## Step 24 — Define the CNN Feature Extractor

The CNN operates on individual 500-bp genomic windows represented using
one-hot encoding.

Its purpose is to learn local sequence features such as nucleotide
patterns and motifs that may contribute to antimicrobial resistance.

The CNN does not directly produce the final genome-level prediction.

Instead, it transforms each genomic window into a lower-dimensional
feature representation (window embedding).

These window embeddings are subsequently aggregated using attention-based
multiple-instance learning to produce a genome-level prediction.

In [40]:
%pip install torch

Requirement already satisfied: torch in /usr/local/lib/python3.13/dist-packages (2.11.0+cu128)
Requirement already satisfied: filelock in /usr/local/lib/python3.13/dist-packages (from torch) (3.32.5)
Requirement already satisfied: typing-extensions>=4.10.0 in /usr/local/lib/python3.13/dist-packages (from torch) (4.16.0)
Requirement already satisfied: setuptools<82 in /usr/local/lib/python3.13/dist-packages (from torch) (81.0.0)
Requirement already satisfied: sympy>=1.13.3 in /usr/local/lib/python3.13/dist-packages (from torch) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in /usr/local/lib/python3.13/dist-packages (from torch) (3.6.1)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.13/dist-packages (from torch) (3.1.6)
Requirement already satisfied: fsspec>=0.8.5 in /usr/local/lib/python3.13/dist-packages (from torch) (2025.12.0)
Requirement already satisfied: cuda-toolkit==12.8.1 in /usr/local/lib/python3.13/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch) (12.8.1)
Requirement already satisfied: cuda-bindings<13,>=12.9.4 in /usr/local/lib/python3.13/dist-packages (from torch) (12.9.7)
Requirement already satisfied: nvidia-cudnn-cu12==9.19.0.56 in /usr/local/lib/python3.13/dist-packages (from torch) (9.19.0.56)
Requirement already satisfied: nvidia-cusparselt-cu12==0.7.1 in /usr/local/lib/python3.13/dist-packages (from torch) (0.7.1)
Requirement already satisfied: nvidia-nccl-cu12==2.28.9 in /usr/local/lib/python3.13/dist-packages (from torch) (2.28.9)
Requirement already satisfied: nvidia-nvshmem-cu12==3.4.5 in /usr/local/lib/python3.13/dist-packages (from torch) (3.4.5)
Requirement already satisfied: triton==3.6.0 in /usr/local/lib/python3.13/dist-packages (from torch) (3.6.0)
Requirement already satisfied: nvidia-cublas-cu12==12.8.4.1.* in /usr/local/lib/python3.13/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch) (12.8.4.1)
Requirement already satisfied: nvidia-cuda-runtime-cu12==12.8.90.* in /usr/local/lib/python3.13/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch) (12.8.90)
Requirement already satisfied: nvidia-cufft-cu12==11.3.3.83.* in /usr/local/lib/python3.13/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch) (11.3.3.83)
Requirement already satisfied: nvidia-cufile-cu12==1.13.1.3.* in /usr/local/lib/python3.13/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch) (1.13.1.3)
Requirement already satisfied: nvidia-cuda-cupti-cu12==12.8.90.* in /usr/local/lib/python3.13/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch) (12.8.90)
Requirement already satisfied: nvidia-curand-cu12==10.3.9.90.* in /usr/local/lib/python3.13/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch) (10.3.9.90)
Requirement already satisfied: nvidia-cusolver-cu12==11.7.3.90.* in /usr/local/lib/python3.13/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch) (11.7.3.90)
Requirement already satisfied: nvidia-cusparse-cu12==12.5.8.93.* in /usr/local/lib/python3.13/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch) (12.5.8.93)
Requirement already satisfied: nvidia-nvjitlink-cu12==12.8.93.* in /usr/local/lib/python3.13/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch) (12.8.93)
Requirement already satisfied: nvidia-cuda-nvrtc-cu12==12.8.93.* in /usr/local/lib/python3.13/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch) (12.8.93)
Requirement already satisfied: nvidia-nvtx-cu12==12.8.90.* in /usr/local/lib/python3.13/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch) (12.8.90)
Requirement already satisfied: cuda-pathfinder~=1.1 in /usr/local/lib/python3.13/dist-packages (from cuda-bindings<13,>=12.9.4->torch) (1.8.0)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.13/dist-packages (from sympy>=1.13.3->torch) (1.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.13/dist-packages (from jinja2->torch) (3.0.3)
Note: you may need to restart the kernel to use updated packages.

## Step 23 — CNN Feature Extraction

A convolutional neural network (CNN) is used to learn local sequence patterns
from one-hot encoded 500-bp genomic windows.

Each window is represented as:

    (500, 4)

where the four channels correspond to the nucleotide bases A, C, G, and T.

PyTorch Conv1D layers expect the input in the format:

    (batch_size, channels, sequence_length)

Therefore, each encoded window is rearranged from:

    (batch_size, 500, 4)

to:

    (batch_size, 4, 500)

The CNN processes each genomic window independently and produces a
128-dimensional embedding for every window.

These window-level embeddings are subsequently passed to the attention-based
multiple-instance learning (MIL) component, which aggregates information across
all windows belonging to the same genome.

The CNN is therefore a feature extractor rather than the final genome-level
classifier.

In [41]:
import torch
import torch.nn as nn


class GenomeCNN(nn.Module):
    """
    CNN feature extractor for one-hot encoded DNA windows.

    Input:
        (batch_size, 500, 4)

    Output:
        (batch_size, 128)

    Each 500-bp genomic window is converted into a
    128-dimensional learned embedding.
    """

    def __init__(self):
        super().__init__()

        self.conv1 = nn.Conv1d(
            in_channels=4,
            out_channels=64,
            kernel_size=15,
            padding=7
        )

        self.conv2 = nn.Conv1d(
            in_channels=64,
            out_channels=128,
            kernel_size=15,
            padding=7
        )

        self.relu = nn.ReLU()

        self.pool = nn.MaxPool1d(
            kernel_size=2
        )

        self.global_pool = nn.AdaptiveMaxPool1d(1)

        self.embedding = nn.Linear(
            128,
            128
        )

    def forward(self, x):
        """
        Forward pass.

        Input:
            x shape = (batch_size, 500, 4)

        Output:
            shape = (batch_size, 128)
        """

        # Rearrange for Conv1D:
        # (batch, 500, 4) → (batch, 4, 500)
        x = x.permute(0, 2, 1)

        x = self.relu(self.conv1(x))
        x = self.pool(x)

        x = self.relu(self.conv2(x))
        x = self.pool(x)

        # Global pooling across sequence positions
        x = self.global_pool(x)

        # Remove final sequence dimension
        x = x.squeeze(-1)

        # Produce final window embedding
        x = self.embedding(x)

        return x

In [42]:
# Create the CNN feature extractor

cnn = GenomeCNN()

print(cnn)

GenomeCNN(
  (conv1): Conv1d(4, 64, kernel_size=(15,), stride=(1,), padding=(7,))
  (conv2): Conv1d(64, 128, kernel_size=(15,), stride=(1,), padding=(7,))
  (relu): ReLU()
  (pool): MaxPool1d(kernel_size=2, stride=2, padding=0, dilation=1, ceil_mode=False)
  (global_pool): AdaptiveMaxPool1d(output_size=1)
  (embedding): Linear(in_features=128, out_features=128, bias=True)
)

In [43]:
# Take the first 128 encoded windows from the representative genome

test_batch = encoded_windows_array[:128]

print("Input shape:", test_batch.shape)

# Convert NumPy array to PyTorch tensor
test_tensor = torch.tensor(
    test_batch,
    dtype=torch.float32
)

# Pass through CNN
with torch.no_grad():
    test_embeddings = cnn(test_tensor)

print("Output shape:", test_embeddings.shape)

Input shape: (128, 500, 4)
Output shape: torch.Size([128, 128])

## Step 25 — Attention-Based Multiple-Instance Learning

The CNN produces a learned embedding for each genomic window.

However, the final prediction is made at the genome level rather than the
window level.

Therefore, all windows belonging to a genome are treated as a single
multiple-instance learning (MIL) bag.

For a genome containing N windows:

    Window 1 → embedding 1
    Window 2 → embedding 2
    ...
    Window N → embedding N

An attention mechanism learns an importance weight for each window embedding.

The attention weights determine which genomic regions contribute more strongly
to the genome-level representation.

The weighted window embeddings are then aggregated into a single genome
embedding, which is used for Resistant/Susceptible classification.

This allows the model to learn which genomic regions are most informative for
ciprofloxacin resistance without assigning an independent resistance label
to every window.

In [45]:
import torch
import torch.nn as nn


class AttentionMIL(nn.Module):
    """
    Attention-based multiple-instance learning aggregator.

    Input:
        (number_of_windows, 128)

    Output:
        genome_embedding: (128,)
        attention_weights: (number_of_windows,)
        prediction_logit: scalar
    """

    def __init__(self, embedding_dim=128):
        super().__init__()

        self.attention = nn.Sequential(
            nn.Linear(embedding_dim, 64),
            nn.Tanh(),
            nn.Linear(64, 1)
        )

        self.classifier = nn.Linear(
            embedding_dim,
            1
        )

    def forward(self, embeddings):
        """
        embeddings:
            Tensor of shape (number_of_windows, embedding_dim)
        """

        # Calculate an attention score for every window
        attention_scores = self.attention(embeddings)

        # Convert scores into normalized attention weights
        attention_weights = torch.softmax(
            attention_scores,
            dim=0
        )

        # Weighted aggregation of all window embeddings
        genome_embedding = torch.sum(
            attention_weights * embeddings,
            dim=0
        )

        # Genome-level prediction
        prediction_logit = self.classifier(
            genome_embedding
        )

        return (
            genome_embedding,
            attention_weights.squeeze(-1),
            prediction_logit.squeeze(-1)
        )

In [46]:
# Create the attention-based MIL aggregator

mil = AttentionMIL(
    embedding_dim=128
)

print(mil)

AttentionMIL(
  (attention): Sequential(
    (0): Linear(in_features=128, out_features=64, bias=True)
    (1): Tanh()
    (2): Linear(in_features=64, out_features=1, bias=True)
  )
  (classifier): Linear(in_features=128, out_features=1, bias=True)
)

In [47]:
# Test attention MIL on the CNN embeddings

with torch.no_grad():
    genome_embedding, attention_weights, prediction_logit = mil(
        test_embeddings
    )

print("Window embeddings shape:", test_embeddings.shape)
print("Genome embedding shape:", genome_embedding.shape)
print("Attention weights shape:", attention_weights.shape)
print("Prediction logit shape:", prediction_logit.shape)

print("\nAttention weights sum:", attention_weights.sum().item())

Window embeddings shape: torch.Size([128, 128])
Genome embedding shape: torch.Size([128])
Attention weights shape: torch.Size([128])
Prediction logit shape: torch.Size([])

Attention weights sum: 1.000000238418579

## Step 27 — Combined CNN and Attention-MIL Model

The complete model combines the CNN feature extractor with the
attention-based multiple-instance learning (MIL) aggregator.

For each genome:

1. Genomic windows are generated from the FASTA sequence.
2. Windows are one-hot encoded.
3. Windows are processed through the CNN in memory-efficient batches.
4. The CNN produces a learned embedding for every window.
5. Embeddings from all windows belonging to the genome are combined.
6. Attention MIL assigns an importance weight to each window.
7. The weighted embeddings are aggregated into a single genome-level
   representation.
8. A classifier predicts ciprofloxacin resistance or susceptibility.

The CNN therefore learns local sequence representations, while the
attention-MIL component learns which genomic regions are most informative
for the genome-level AMR phenotype.

In [48]:
class GenomeAMRModel(nn.Module):
    """
    Complete genome-level AMR prediction model.

    CNN:
        Converts each 500-bp DNA window into a 128-dimensional embedding.

    Attention MIL:
        Aggregates all window embeddings belonging to one genome and
        produces a genome-level prediction.
    """

    def __init__(self):
        super().__init__()

        self.cnn = GenomeCNN(
        )

        self.mil = AttentionMIL(
            embedding_dim=128
        )

    def forward(self, window_batch):
        """
        Input:
            window_batch:
                (number_of_windows, 500, 4)

        Output:
            genome_embedding:
                (128,)

            attention_weights:
                (number_of_windows,)

            prediction_logit:
                scalar
        """

        # Extract a learned representation for every window
        window_embeddings = self.cnn(
            window_batch
        )

        # Aggregate window representations at genome level
        genome_embedding, attention_weights, prediction_logit = self.mil(
            window_embeddings
        )

        return (
            genome_embedding,
            attention_weights,
            prediction_logit
        )

In [49]:
# Create the complete CNN + Attention-MIL model

model = GenomeAMRModel()

print(model)

GenomeAMRModel(
  (cnn): GenomeCNN(
    (conv1): Conv1d(4, 64, kernel_size=(15,), stride=(1,), padding=(7,))
    (conv2): Conv1d(64, 128, kernel_size=(15,), stride=(1,), padding=(7,))
    (relu): ReLU()
    (pool): MaxPool1d(kernel_size=2, stride=2, padding=0, dilation=1, ceil_mode=False)
    (global_pool): AdaptiveMaxPool1d(output_size=1)
    (embedding): Linear(in_features=128, out_features=128, bias=True)
  )
  (mil): AttentionMIL(
    (attention): Sequential(
      (0): Linear(in_features=128, out_features=64, bias=True)
      (1): Tanh()
      (2): Linear(in_features=64, out_features=1, bias=True)
    )
    (classifier): Linear(in_features=128, out_features=1, bias=True)
  )
)

## Step 28 — Test the Combined CNN + Attention-MIL Model

The complete model combines the CNN feature extractor and attention-based
multiple-instance learning into a single genome-level prediction pipeline.

A batch of one-hot encoded genomic windows is first processed by the shared
CNN to obtain window-level embeddings. These embeddings are then aggregated
by the attention-MIL module into a single genome-level representation and
prediction.

This test verifies that the complete forward pass works correctly before
training is implemented.

In [51]:
# Find the window-batching generator currently defined in the notebook

[name for name in globals() if "batch" in name.lower() and callable(globals()[name])]

['generate_window_batches']

In [52]:
# Test the complete CNN + Attention-MIL model

# Generate the first streaming batch from the representative genome
test_batch = next(
    generate_window_batches(
        representative_windows,
        batch_size=128
    )
)

print("Input batch shape:", test_batch.shape)

# Convert NumPy array to PyTorch tensor
test_tensor = torch.tensor(
    test_batch,
    dtype=torch.float32
)

# Run the complete CNN + Attention-MIL model
with torch.no_grad():
    genome_embedding, attention_weights, prediction_logit = model(test_tensor)

print("Genome embedding shape:", genome_embedding.shape)
print("Attention weights shape:", attention_weights.shape)
print("Prediction logit:", prediction_logit)
print("Prediction shape:", prediction_logit.shape)

Input batch shape: (128, 500, 4)
Genome embedding shape: torch.Size([128])
Attention weights shape: torch.Size([128])
Prediction logit: tensor(-0.1620)
Prediction shape: torch.Size([])

## Step 29 — Genome-Level Streaming Inference

The complete genome contains thousands of genomic windows, which cannot be processed
simultaneously without unnecessary memory usage.

The streaming pipeline processes genomic windows in batches:

1. Generate 500-bp windows from the genome.
2. One-hot encode a batch of windows.
3. Pass the batch through the CNN.
4. Collect the resulting 128-dimensional window embeddings.
5. Continue until all genome windows have been processed.
6. Aggregate the complete set of window embeddings using Attention-MIL.
7. Produce one genome-level prediction.

This allows the model to process complete bacterial genomes while keeping
memory usage bounded by the batch size.

In [53]:
# Process the complete representative genome in streaming batches

batch_size = 128

embedding_batches = []
total_windows_processed = 0

with torch.no_grad():

    for batch_number, batch in enumerate(
        generate_window_batches(
            representative_windows,
            batch_size=batch_size
        ),
        start=1
    ):

        # Convert NumPy batch to PyTorch tensor
        batch_tensor = torch.tensor(
            batch,
            dtype=torch.float32
        )

        # Extract a 128-dimensional embedding for each window
        batch_embeddings = model.cnn(batch_tensor)

        # Move embeddings to CPU and store them
        embedding_batches.append(
            batch_embeddings.cpu()
        )

        total_windows_processed += batch_tensor.shape[0]

        # Show the first few batches
        if batch_number <= 3:
            print(
                f"Batch {batch_number}: "
                f"input {batch_tensor.shape} → "
                f"embeddings {batch_embeddings.shape}"
            )

# Combine all window embeddings into one genome-level collection
all_window_embeddings = torch.cat(
    embedding_batches,
    dim=0
)

print("\nTotal windows processed:", total_windows_processed)
print("Expected windows:", len(representative_windows))
print(
    "All window embeddings shape:",
    all_window_embeddings.shape
)

if total_windows_processed == len(representative_windows):
    print("\n✓ Complete genome processed exactly once.")
else:
    print("\n✗ Window count mismatch.")

Batch 1: input torch.Size([128, 500, 4]) → embeddings torch.Size([128, 128])
Batch 2: input torch.Size([128, 500, 4]) → embeddings torch.Size([128, 128])
Batch 3: input torch.Size([128, 500, 4]) → embeddings torch.Size([128, 128])

Total windows processed: 10885
Expected windows: 10885
All window embeddings shape: torch.Size([10885, 128])

✓ Complete genome processed exactly once.

In [56]:
# Apply Attention-MIL to all window embeddings from the genome

with torch.no_grad():

    genome_embedding, attention_weights, prediction_logit = model.mil(
        all_window_embeddings
    )

print("Window embeddings shape:", all_window_embeddings.shape)
print("Genome embedding shape:", genome_embedding.shape)
print("Attention weights shape:", attention_weights.shape)
print("Prediction logit:", prediction_logit)
print("Attention weights sum:", attention_weights.sum().item())

Window embeddings shape: torch.Size([10885, 128])
Genome embedding shape: torch.Size([128])
Attention weights shape: torch.Size([10885])
Prediction logit: tensor(-0.1614)
Attention weights sum: 1.0000009536743164

In [57]:
# Validate the attention distribution

attention_np = attention_weights.detach().cpu().numpy()

print("Number of attention weights:", len(attention_np))
print("Minimum attention weight:", attention_np.min())
print("Maximum attention weight:", attention_np.max())
print("Mean attention weight:", attention_np.mean())
print("Sum of attention weights:", attention_np.sum())

# Check that all weights are non-negative
non_negative = np.all(attention_np >= 0)

# Check that they sum approximately to 1
sums_to_one = np.isclose(attention_np.sum(), 1.0)

print("\nNon-negative weights:", non_negative)
print("Weights sum to 1:", sums_to_one)

if non_negative and sums_to_one:
    print("\n✓ Attention distribution validation passed.")
else:
    print("\n✗ Attention distribution validation failed.")

Number of attention weights: 10885
Minimum attention weight: 8.944176e-05
Maximum attention weight: 9.4278585e-05
Mean attention weight: 9.186965e-05
Sum of attention weights: 1.0000012

Non-negative weights: True
Weights sum to 1: True

✓ Attention distribution validation passed.

## Step 30 — Define Genome-Level Training Data Stream

During training, each genome is treated as one multiple-instance learning
(MIL) bag.

Windows are generated and one-hot encoded in batches rather than storing
the complete window dataset in memory.

For each genome:

1. Load the corresponding FASTA file.
2. Parse the genome into contigs.
3. Generate windows independently within each contig.
4. One-hot encode windows in batches.
5. Return the batches together with the genome-level label.

The genome label is applied only after all window embeddings have been
aggregated by Attention-MIL.

In [58]:
def generate_genome_training_batches(
    genome_id,
    batch_size=WINDOW_BATCH_SIZE
):
    """
    Stream one-hot encoded window batches from a single genome.

    The genome remains one MIL bag.
    Windows are generated contig-by-contig and processed in batches.

    Yields:
        batch_tensor:
            NumPy array of shape
            (batch_size, 500, 4)

        label:
            Genome-level binary phenotype label.
    """

    # Locate FASTA
    fasta_path = genome_dir / f"{genome_id}.fna"

    if not fasta_path.exists():
        raise FileNotFoundError(
            f"FASTA file not found for Genome ID: {genome_id}"
        )

    # Get genome-level label
    genome_row = model_df[
        model_df["Genome ID"] == genome_id
    ]

    if len(genome_row) != 1:
        raise ValueError(
            f"Expected exactly one phenotype record for {genome_id}, "
            f"found {len(genome_row)}"
        )

    label = int(genome_row.iloc[0]["Label"])

    # Parse genome
    contigs = parse_fasta(fasta_path)

    # Process contigs independently
    batch_windows = []

    for contig_id, sequence in contigs.items():

        # Generate windows from this contig
        contig_windows = generate_windows(
            sequence,
            window_size=WINDOW_SIZE,
            stride=STRIDE
        )

        for window in contig_windows:

            batch_windows.append(
                window["Sequence"]
            )

            # Yield a full batch
            if len(batch_windows) == batch_size:

                batch_encoded = np.stack([
                    one_hot_encode(seq)
                    for seq in batch_windows
                ])

                yield batch_encoded, label

                batch_windows = []

    # Yield final partial batch
    if batch_windows:

        batch_encoded = np.stack([
            one_hot_encode(seq)
            for seq in batch_windows
        ])

        yield batch_encoded, label

In [59]:
# Test genome-level training batches

training_batch_count = 0
training_window_count = 0
training_labels = []

for batch, label in generate_genome_training_batches(
    test_genome_id,
    batch_size=WINDOW_BATCH_SIZE
):

    training_batch_count += 1
    training_window_count += batch.shape[0]
    training_labels.append(label)

    if training_batch_count <= 3:
        print(
            f"Batch {training_batch_count}:",
            batch.shape,
            "| Label:",
            label
        )

print("\nTotal batches:", training_batch_count)
print("Total windows:", training_window_count)
print("Expected windows:", len(test_genome_windows))
print("Unique labels:", set(training_labels))

Batch 1: (128, 500, 4) | Label: 0
Batch 2: (128, 500, 4) | Label: 0
Batch 3: (128, 500, 4) | Label: 0

Total batches: 86
Total windows: 10885
Expected windows: 10885
Unique labels: {0}

## Step 31 — Define Genome-Level Training Forward Pass

A complete genome may contain thousands of windows, so windows are passed
through the CNN in smaller batches.

The resulting window embeddings are retained for the current genome and
then passed together to Attention-MIL.

The loss is therefore calculated from a single genome-level prediction,
preserving the MIL formulation.

In [62]:
def forward_genome(
    model,
    genome_id,
    batch_size=WINDOW_BATCH_SIZE,
    device="cpu"
):
    """
    Perform a differentiable forward pass for one genome.

    Returns:
        genome_embedding
        attention_weights
        prediction_logit
        label
    """

    embedding_batches = []
    label = None

    for batch, batch_label in generate_genome_training_batches(
        genome_id,
        batch_size=batch_size
    ):

        # Convert NumPy → PyTorch
        batch_tensor = torch.tensor(
            batch,
            dtype=torch.float32,
            device=device
        )

        # CNN forward pass
        batch_embeddings = model.cnn(
            batch_tensor
        )

        embedding_batches.append(
            batch_embeddings
        )

        label = batch_label

    # Combine all windows belonging to this genome
    all_embeddings = torch.cat(
        embedding_batches,
        dim=0
    )

    # Attention-MIL aggregation
    (
        genome_embedding,
        attention_weights,
        prediction_logit
    ) = model.mil(
        all_embeddings
    )

    return (
        genome_embedding,
        attention_weights,
        prediction_logit,
        label
    )

In [63]:
# Test differentiable genome-level forward pass

model.train()

(
    genome_embedding,
    attention_weights,
    prediction_logit,
    label
) = forward_genome(
    model,
    test_genome_id,
    batch_size=WINDOW_BATCH_SIZE
)

print("Genome embedding:", genome_embedding.shape)
print("Attention weights:", attention_weights.shape)
print("Prediction logit:", prediction_logit.shape)
print("Genome label:", label)

print("\nNumber of windows:", len(attention_weights))
print("Attention sum:", attention_weights.sum().item())

Genome embedding: torch.Size([128])
Attention weights: torch.Size([10885])
Prediction logit: torch.Size([])
Genome label: 0

Number of windows: 10885
Attention sum: 1.0000009536743164

## Step 32 — Test Genome-Level Loss and Gradient Flow

The model predicts antibiotic resistance at the genome level.

Because the task is binary classification (Resistant vs Susceptible),
BCEWithLogitsLoss is used directly on the genome-level prediction logit.

This step verifies that gradients can flow through the complete model:

Genome windows → CNN → Attention MIL → classifier → loss.

In [64]:
# Step 32 — Test genome-level loss and gradient flow

model.train()

# Clear any existing gradients
model.zero_grad()

# Forward pass through one complete genome
(
    genome_embedding,
    attention_weights,
    prediction_logit,
    label
) = forward_genome(
    model,
    test_genome_id,
    batch_size=WINDOW_BATCH_SIZE
)

# Convert genome label to PyTorch tensor
label_tensor = torch.tensor(
    float(label),
    dtype=torch.float32,
    device=prediction_logit.device
)

# Binary classification loss
criterion = torch.nn.BCEWithLogitsLoss()

loss = criterion(
    prediction_logit,
    label_tensor
)

print("Prediction logit:", prediction_logit.item())
print("Genome label:", label)
print("Loss:", loss.item())

# Backpropagation
loss.backward()

print("\nGradient flow verified.")

Prediction logit: -0.1613689512014389
Genome label: 0
Loss: 0.6157141327857971

Gradient flow verified.

In [66]:
# Check that trainable model parameters received gradients

gradient_parameters = 0
gradient_norm = 0.0

for name, parameter in model.named_parameters():

    if parameter.requires_grad and parameter.grad is not None:

        gradient_parameters += 1

        gradient_norm += (
            parameter.grad.detach().norm().item()
        ) ** 2

gradient_norm = gradient_norm ** 0.5

print("Parameters with gradients:", gradient_parameters)
print("Total gradient norm:", gradient_norm)

Parameters with gradients: 12
Total gradient norm: 1.606555056970178

## Step 33 — Test One-Genome Optimizer Step

The optimizer updates the CNN, Attention-MIL, and classifier parameters
using the genome-level loss.

A single training step is performed first to verify that model parameters
actually change after backpropagation and optimization.

In [67]:
# Step 33 — Define loss function and optimizer

criterion = torch.nn.BCEWithLogitsLoss()

optimizer = torch.optim.Adam(
    model.parameters(),
    lr=1e-3
)

print("Loss function:", criterion)
print("Optimizer:", optimizer)

Loss function: BCEWithLogitsLoss()
Optimizer: Adam (
Parameter Group 0
    amsgrad: False
    betas: (0.9, 0.999)
    capturable: False
    decoupled_weight_decay: False
    differentiable: False
    eps: 1e-08
    foreach: None
    fused: None
    lr: 0.001
    maximize: False
    weight_decay: 0
)

In [68]:
# Test one complete optimization step

model.train()

# Clear old gradients
optimizer.zero_grad()

# Save one parameter before the update
parameter_name = "cnn.conv1.weight"

parameter_before = (
    model.cnn.conv1.weight.detach()
    .clone()
)

# Forward pass
(
    genome_embedding,
    attention_weights,
    prediction_logit,
    label
) = forward_genome(
    model,
    test_genome_id,
    batch_size=WINDOW_BATCH_SIZE
)

# Genome-level target
label_tensor = torch.tensor(
    float(label),
    dtype=torch.float32,
    device=prediction_logit.device
)

# Calculate loss
loss = criterion(
    prediction_logit,
    label_tensor
)

# Backpropagation
loss.backward()

# Update parameters
optimizer.step()

# Compare parameter after update
parameter_after = (
    model.cnn.conv1.weight.detach()
)

parameter_change = (
    parameter_after - parameter_before
).norm().item()

print("Genome label:", label)
print("Prediction logit:", prediction_logit.item())
print("Loss:", loss.item())
print("Parameter change:", parameter_change)

Genome label: 0
Prediction logit: -0.1613689512014389
Loss: 0.6157141327857971
Parameter change: 0.06196416914463043

## Step 34 — Fresh Model Initialization and Training Setup

In [69]:
# Step 34 — Initialize the model for the actual experiment

import random
from pathlib import Path
import numpy as np
import torch
from sklearn.metrics import accuracy_score, roc_auc_score

# Reproducibility
SEED = 42
random.seed(SEED)
np.random.seed(SEED)
torch.manual_seed(SEED)

if torch.cuda.is_available():
    torch.cuda.manual_seed_all(SEED)

# Select available hardware
device = torch.device(
    "cuda" if torch.cuda.is_available() else "cpu"
)

# Fresh model: discard the optimizer-test update
model = GenomeAMRModel().to(device)

# Training configuration
criterion = torch.nn.BCEWithLogitsLoss()

optimizer = torch.optim.Adam(
    model.parameters(),
    lr=1e-3
)

# Use the existing genome-level splits
train_genome_ids = train_df["Genome ID"].astype(str).tolist()
val_genome_ids = val_df["Genome ID"].astype(str).tolist()
test_genome_ids = test_df["Genome ID"].astype(str).tolist()

# Verify no leakage between partitions
assert set(train_genome_ids).isdisjoint(val_genome_ids)
assert set(train_genome_ids).isdisjoint(test_genome_ids)
assert set(val_genome_ids).isdisjoint(test_genome_ids)

assert set(train_df["Label"].unique()).issubset({0, 1})
assert set(val_df["Label"].unique()).issubset({0, 1})
assert set(test_df["Label"].unique()).issubset({0, 1})

print("Device:", device)
print("Training genomes:", len(train_genome_ids))
print("Validation genomes:", len(val_genome_ids))
print("Test genomes:", len(test_genome_ids))
print("Training labels:", train_df["Label"].value_counts().to_dict())
print("Validation labels:", val_df["Label"].value_counts().to_dict())
print("Fresh model initialized.")

Device: cuda
Training genomes: 796
Validation genomes: 171
Test genomes: 171
Training labels: {0: 464, 1: 332}
Validation labels: {0: 100, 1: 71}
Fresh model initialized.

In [71]:
# Quick GPU and data-path check before full training

print("GPU:", torch.cuda.get_device_name(0))
print("Model device:", next(model.parameters()).device)
print("Training genome example:", train_genome_ids[0])

example_path = genome_dir / f"{train_genome_ids[0]}.fna"
print("Example FASTA exists:", example_path.exists())
print("Example FASTA path:", example_path)

assert torch.cuda.is_available()
assert next(model.parameters()).is_cuda
assert example_path.exists()

print("GPU and training data checks passed.")

GPU: Tesla T4
Model device: cuda:0
Training genome example: 1280.59769
Example FASTA exists: True
Example FASTA path: /kaggle/input/datasets/prajaktananda1905/amr-data/data/genomes/1280.59769.fna
GPU and training data checks passed.

In [ ]:

# Step 35 — Genome-level CNN + Attention-MIL training
# Includes periodic checkpoints and resume support.

import gc
import time
import random
import numpy as np
import pandas as pd
import torch

from pathlib import Path
from sklearn.metrics import accuracy_score, roc_auc_score

# --------------------------------------------------
# 1. Training configuration
# --------------------------------------------------

EPOCHS = 10
CHECKPOINT_EVERY = 10

MODEL_DIR = Path("/kaggle/working/models")
MODEL_DIR.mkdir(parents=True, exist_ok=True)

BEST_MODEL_PATH = MODEL_DIR / "best_amr_genome_cnn.pt"
LATEST_MODEL_PATH = MODEL_DIR / "latest_amr_genome_cnn.pt"
TEMP_MODEL_PATH = MODEL_DIR / "latest_amr_genome_cnn.tmp"

best_val_loss = float("inf")
history = []

# --------------------------------------------------
# 2. Resume from the latest checkpoint if available
# --------------------------------------------------

start_epoch = 1
resume_train_index = 0
resume_shuffled_ids = None
resume_train_losses = []

if LATEST_MODEL_PATH.exists():
    checkpoint = torch.load(
        LATEST_MODEL_PATH,
        map_location=device,
        weights_only=False
    )

    model.load_state_dict(checkpoint["model_state_dict"])
    optimizer.load_state_dict(checkpoint["optimizer_state_dict"])

    start_epoch = checkpoint.get("epoch", 1)
    resume_train_index = checkpoint.get("next_train_index", 0)
    resume_shuffled_ids = checkpoint.get("shuffled_ids")
    resume_train_losses = checkpoint.get("train_losses", [])
    best_val_loss = checkpoint.get("best_val_loss", float("inf"))
    history = checkpoint.get("history", [])

    print("Checkpoint found — resuming training.")
    print("Resume epoch:", start_epoch)
    print("Next training genome index:", resume_train_index + 1)

else:
    print("No previous checkpoint found — starting fresh.")

# --------------------------------------------------
# 3. Save checkpoints safely
# --------------------------------------------------

def save_training_checkpoint(
    epoch,
    next_train_index,
    shuffled_ids,
    train_losses,
    epoch_complete=False
):
    checkpoint_data = {
        "epoch": epoch,
        "next_train_index": next_train_index,
        "shuffled_ids": shuffled_ids,
        "train_losses": train_losses,
        "epoch_complete": epoch_complete,
        "model_state_dict": model.state_dict(),
        "optimizer_state_dict": optimizer.state_dict(),
        "best_val_loss": best_val_loss,
        "history": history,
        "seed": SEED
    }

    torch.save(checkpoint_data, TEMP_MODEL_PATH)
    TEMP_MODEL_PATH.replace(LATEST_MODEL_PATH)

# --------------------------------------------------
# 4. Training
# --------------------------------------------------

print("\nDevice:", device)
print(
    "GPU:",
    torch.cuda.get_device_name(0)
    if torch.cuda.is_available() else "CPU"
)
print("Training genomes:", len(train_genome_ids))
print("Validation genomes:", len(val_genome_ids))
print("Test genomes:", len(test_genome_ids))
print("Checkpoint interval:", CHECKPOINT_EVERY, "genomes")
print("\nStarting training...\n")

for epoch in range(start_epoch, EPOCHS + 1):

    epoch_start = time.time()
    model.train()

    # Resume the unfinished epoch, or create a new shuffled order.
    if (
        epoch == start_epoch
        and resume_shuffled_ids is not None
        and resume_train_index > 0
    ):
        shuffled_ids = resume_shuffled_ids
        train_losses = resume_train_losses
        first_index = resume_train_index
    else:
        shuffled_ids = train_genome_ids.copy()
        random.shuffle(shuffled_ids)
        train_losses = []
        first_index = 0

    print(f"\n========== Epoch {epoch}/{EPOCHS} ==========")

    # -------------------------
    # Training genomes
    # -------------------------

    for index in range(first_index, len(shuffled_ids)):

        genome_id = shuffled_ids[index]
        genome_start = time.time()

        print(
            f"Epoch {epoch}/{EPOCHS} | "
            f"Genome {index + 1}/{len(shuffled_ids)} | "
            f"ID: {genome_id}",
            flush=True
        )

        optimizer.zero_grad(set_to_none=True)

        genome_embedding, attention_weights, logit, label = forward_genome(
            model,
            genome_id,
            batch_size=WINDOW_BATCH_SIZE,
            device=device
        )

        target = torch.tensor(
            float(label),
            dtype=torch.float32,
            device=device
        )

        loss = criterion(logit.reshape(()), target)
        loss.backward()
        optimizer.step()

        train_losses.append(loss.item())

        genome_elapsed = (time.time() - genome_start) / 60

        del genome_embedding, attention_weights, logit, target, loss

        if (index + 1) % CHECKPOINT_EVERY == 0:
            save_training_checkpoint(
                epoch=epoch,
                next_train_index=index + 1,
                shuffled_ids=shuffled_ids,
                train_losses=train_losses
            )

            print(
                f"Checkpoint saved | "
                f"Completed {index + 1}/{len(shuffled_ids)} genomes | "
                f"Last genome: {genome_elapsed:.2f} min",
                flush=True
            )

        gc.collect()

    train_loss = float(np.mean(train_losses))

    # -------------------------
    # Validation
    # -------------------------

    model.eval()

    val_losses = []
    val_labels = []
    val_probs = []

    with torch.no_grad():
        for i, genome_id in enumerate(val_genome_ids, start=1):

            print(
                f"Validation {i}/{len(val_genome_ids)} | "
                f"ID: {genome_id}",
                flush=True
            )

            genome_embedding, attention_weights, logit, label = forward_genome(
                model,
                genome_id,
                batch_size=WINDOW_BATCH_SIZE,
                device=device
            )

            target = torch.tensor(
                float(label),
                dtype=torch.float32,
                device=device
            )

            val_losses.append(
                criterion(logit.reshape(()), target).item()
            )
            val_labels.append(int(label))
            val_probs.append(torch.sigmoid(logit).item())

            del genome_embedding, attention_weights, logit, target

    val_loss = float(np.mean(val_losses))
    val_predictions = [int(p >= 0.5) for p in val_probs]

    val_accuracy = accuracy_score(val_labels, val_predictions)

    val_auc = (
        roc_auc_score(val_labels, val_probs)
        if len(set(val_labels)) == 2
        else float("nan")
    )

    # -------------------------
    # Record metrics
    # -------------------------

    epoch_result = {
        "epoch": epoch,
        "train_loss": train_loss,
        "val_loss": val_loss,
        "val_accuracy": val_accuracy,
        "val_auc": val_auc
    }

    history.append(epoch_result)

    elapsed = (time.time() - epoch_start) / 60

    print(f"\nEpoch {epoch}/{EPOCHS} complete")
    print(f"Train loss:          {train_loss:.4f}")
    print(f"Validation loss:     {val_loss:.4f}")
    print(f"Validation accuracy: {val_accuracy:.4f}")
    print(f"Validation ROC-AUC:  {val_auc:.4f}")
    print(f"Epoch time:          {elapsed:.1f} minutes")

    # -------------------------
    # Save best model
    # -------------------------

    if val_loss < best_val_loss:
        best_val_loss = val_loss

        best_checkpoint = {
            "epoch": epoch,
            "model_state_dict": model.state_dict(),
            "optimizer_state_dict": optimizer.state_dict(),
            "train_loss": train_loss,
            "val_loss": val_loss,
            "val_accuracy": val_accuracy,
            "val_auc": val_auc,
            "history": history,
            "seed": SEED
        }

        torch.save(best_checkpoint, BEST_MODEL_PATH)
        print("Best model checkpoint saved.")

    # Save a checkpoint marking this epoch as complete.
    if epoch < EPOCHS:
        save_training_checkpoint(
            epoch=epoch + 1,
            next_train_index=0,
            shuffled_ids=None,
            train_losses=[],
            epoch_complete=True
        )
    else:
        save_training_checkpoint(
            epoch=epoch,
            next_train_index=len(shuffled_ids),
            shuffled_ids=shuffled_ids,
            train_losses=train_losses,
            epoch_complete=True
        )

    print("Latest checkpoint saved.")
    print("-" * 55)

    # Prepare for the next epoch.
    resume_train_index = 0
    resume_shuffled_ids = None
    resume_train_losses = []

    gc.collect()

    if torch.cuda.is_available():
        torch.cuda.empty_cache()

print("\nTraining finished.")
print("Best validation loss:", round(best_val_loss, 4))
print("Best model:", BEST_MODEL_PATH)
print("Latest checkpoint:", LATEST_MODEL_PATH)

history_df = pd.DataFrame(history)
display(history_df)

No previous checkpoint found — starting fresh.

Device: cuda
GPU: Tesla T4
Training genomes: 796
Validation genomes: 171
Test genomes: 171
Checkpoint interval: 10 genomes

Starting training...


========== Epoch 1/10 ==========
Epoch 1/10 | Genome 1/796 | ID: 1280.59538
Epoch 1/10 | Genome 2/796 | ID: 1280.59486
Epoch 1/10 | Genome 3/796 | ID: 1280.59308
Epoch 1/10 | Genome 4/796 | ID: 1280.59525
Epoch 1/10 | Genome 5/796 | ID: 1280.9346
Epoch 1/10 | Genome 6/796 | ID: 1280.51746
Epoch 1/10 | Genome 7/796 | ID: 1280.59664
Epoch 1/10 | Genome 8/796 | ID: 1280.9239
Epoch 1/10 | Genome 9/796 | ID: 1280.59597
Epoch 1/10 | Genome 10/796 | ID: 1280.59853
Checkpoint saved | Completed 10/796 genomes | Last genome: 0.05 min
Epoch 1/10 | Genome 11/796 | ID: 1280.59423
Epoch 1/10 | Genome 12/796 | ID: 1280.51766
Epoch 1/10 | Genome 13/796 | ID: 1280.9375
Epoch 1/10 | Genome 14/796 | ID: 1280.15911
Epoch 1/10 | Genome 15/796 | ID: 1280.26069
Epoch 1/10 | Genome 16/796 | ID: 1280.59654
Epoch 1/10 | Genome 17/796 | ID: 1280.26049
Epoch 1/10 | Genome 18/796 | ID: 1280.59454
Epoch 1/10 | Genome 19/796 | ID: 1280.59875
Epoch 1/10 | Genome 20/796 | ID: 1280.59745
Checkpoint saved | Completed 20/796 genomes | Last genome: 0.05 min
Epoch 1/10 | Genome 21/796 | ID: 1280.9197
Epoch 1/10 | Genome 22/796 | ID: 1280.51863
Epoch 1/10 | Genome 23/796 | ID: 1280.59818
Epoch 1/10 | Genome 24/796 | ID: 1280.9273
Epoch 1/10 | Genome 25/796 | ID: 1280.51795
Epoch 1/10 | Genome 26/796 | ID: 1280.9303
Epoch 1/10 | Genome 27/796 | ID: 1280.9216
Epoch 1/10 | Genome 28/796 | ID: 1280.59815
Epoch 1/10 | Genome 29/796 | ID: 1280.59453
Epoch 1/10 | Genome 30/796 | ID: 1280.25983
Checkpoint saved | Completed 30/796 genomes | Last genome: 0.05 min
Epoch 1/10 | Genome 31/796 | ID: 1280.59448
Epoch 1/10 | Genome 32/796 | ID: 1280.59824
Epoch 1/10 | Genome 33/796 | ID: 1280.59505
Epoch 1/10 | Genome 34/796 | ID: 1280.9228
Epoch 1/10 | Genome 35/796 | ID: 1280.59827
Epoch 1/10 | Genome 36/796 | ID: 1280.26004
Epoch 1/10 | Genome 37/796 | ID: 1280.59342
Epoch 1/10 | Genome 38/796 | ID: 1280.5975
Epoch 1/10 | Genome 39/796 | ID: 1280.51815
Epoch 1/10 | Genome 40/796 | ID: 1280.15875
Checkpoint saved | Completed 40/796 genomes | Last genome: 0.05 min
Epoch 1/10 | Genome 41/796 | ID: 1280.59601
Epoch 1/10 | Genome 42/796 | ID: 1280.5962
Epoch 1/10 | Genome 43/796 | ID: 1280.59258
Epoch 1/10 | Genome 44/796 | ID: 1280.9367
Epoch 1/10 | Genome 45/796 | ID: 1280.59529
Epoch 1/10 | Genome 46/796 | ID: 1280.15909
Epoch 1/10 | Genome 47/796 | ID: 1280.59662
Epoch 1/10 | Genome 48/796 | ID: 1280.59361
Epoch 1/10 | Genome 49/796 | ID: 1280.59711
Epoch 1/10 | Genome 50/796 | ID: 1280.59672
Checkpoint saved | Completed 50/796 genomes | Last genome: 0.05 min
Epoch 1/10 | Genome 51/796 | ID: 1280.59407
Epoch 1/10 | Genome 52/796 | ID: 1280.59428
Epoch 1/10 | Genome 53/796 | ID: 1280.9235
Epoch 1/10 | Genome 54/796 | ID: 1280.25982
Epoch 1/10 | Genome 55/796 | ID: 1280.26057
Epoch 1/10 | Genome 56/796 | ID: 1280.59495
Epoch 1/10 | Genome 57/796 | ID: 1280.15889
Epoch 1/10 | Genome 58/796 | ID: 1280.59272
Epoch 1/10 | Genome 59/796 | ID: 1280.15927
Epoch 1/10 | Genome 60/796 | ID: 1280.59681
Checkpoint saved | Completed 60/796 genomes | Last genome: 0.05 min
Epoch 1/10 | Genome 61/796 | ID: 1280.51739
Epoch 1/10 | Genome 62/796 | ID: 1280.59802
Epoch 1/10 | Genome 63/796 | ID: 1280.51839
Epoch 1/10 | Genome 64/796 | ID: 1280.59861
Epoch 1/10 | Genome 65/796 | ID: 1280.59881
Epoch 1/10 | Genome 66/796 | ID: 1280.59382
Epoch 1/10 | Genome 67/796 | ID: 1280.15895
Epoch 1/10 | Genome 68/796 | ID: 1280.59381
Epoch 1/10 | Genome 69/796 | ID: 1280.51833
Epoch 1/10 | Genome 70/796 | ID: 1280.9353
Checkpoint saved | Completed 70/796 genomes | Last genome: 0.06 min
Epoch 1/10 | Genome 71/796 | ID: 1280.5985
Epoch 1/10 | Genome 72/796 | ID: 1280.59619
Epoch 1/10 | Genome 73/796 | ID: 1280.9388
Epoch 1/10 | Genome 74/796 | ID: 1280.9217
Epoch 1/10 | Genome 75/796 | ID: 1280.59868
Epoch 1/10 | Genome 76/796 | ID: 1280.59322
Epoch 1/10 | Genome 77/796 | ID: 1280.59694
Epoch 1/10 | Genome 78/796 | ID: 1280.9339
Epoch 1/10 | Genome 79/796 | ID: 1280.59285
Epoch 1/10 | Genome 80/796 | ID: 1280.59693
Checkpoint saved | Completed 80/796 genomes | Last genome: 0.05 min
Epoch 1/10 | Genome 81/796 | ID: 1280.26016
Epoch 1/10 | Genome 82/796 | ID: 1280.51895
Epoch 1/10 | Genome 83/796 | ID: 1280.9189
Epoch 1/10 | Genome 84/796 | ID: 1280.9304
Epoch 1/10 | Genome 85/796 | ID: 1280.59333
Epoch 1/10 | Genome 86/796 | ID: 1280.7355
Epoch 1/10 | Genome 87/796 | ID: 1280.51774
Epoch 1/10 | Genome 88/796 | ID: 1280.59347
Epoch 1/10 | Genome 89/796 | ID: 1280.59422
Epoch 1/10 | Genome 90/796 | ID: 1280.59458
Checkpoint saved | Completed 90/796 genomes | Last genome: 0.05 min
Epoch 1/10 | Genome 91/796 | ID: 1280.51841
Epoch 1/10 | Genome 92/796 | ID: 1280.59844
Epoch 1/10 | Genome 93/796 | ID: 1280.59887
Epoch 1/10 | Genome 94/796 | ID: 1280.26058
Epoch 1/10 | Genome 95/796 | ID: 1280.59421
Epoch 1/10 | Genome 96/796 | ID: 1280.9201
Epoch 1/10 | Genome 97/796 | ID: 1280.59276
Epoch 1/10 | Genome 98/796 | ID: 1280.7349
Epoch 1/10 | Genome 99/796 | ID: 1280.51837
Epoch 1/10 | Genome 100/796 | ID: 1280.9345
Checkpoint saved | Completed 100/796 genomes | Last genome: 0.05 min
Epoch 1/10 | Genome 101/796 | ID: 1280.59798
Epoch 1/10 | Genome 102/796 | ID: 1280.26063
Epoch 1/10 | Genome 103/796 | ID: 1280.15925
Epoch 1/10 | Genome 104/796 | ID: 1280.51858
Epoch 1/10 | Genome 105/796 | ID: 1280.59366
Epoch 1/10 | Genome 106/796 | ID: 1280.59521
Epoch 1/10 | Genome 107/796 | ID: 1280.59595
Epoch 1/10 | Genome 108/796 | ID: 1280.51742
Epoch 1/10 | Genome 109/796 | ID: 1280.51776
Epoch 1/10 | Genome 110/796 | ID: 1280.59638
Checkpoint saved | Completed 110/796 genomes | Last genome: 0.05 min
Epoch 1/10 | Genome 111/796 | ID: 1280.15891
Epoch 1/10 | Genome 112/796 | ID: 1280.51745
Epoch 1/10 | Genome 113/796 | ID: 1280.9259
Epoch 1/10 | Genome 114/796 | ID: 1280.26039
Epoch 1/10 | Genome 115/796 | ID: 1280.5952
Epoch 1/10 | Genome 116/796 | ID: 1280.59536
Epoch 1/10 | Genome 117/796 | ID: 1280.26054
Epoch 1/10 | Genome 118/796 | ID: 1280.59897
Epoch 1/10 | Genome 119/796 | ID: 1280.51785
Epoch 1/10 | Genome 120/796 | ID: 1280.59399
Checkpoint saved | Completed 120/796 genomes | Last genome: 0.05 min
Epoch 1/10 | Genome 121/796 | ID: 1280.51806
Epoch 1/10 | Genome 122/796 | ID: 1280.59841
Epoch 1/10 | Genome 123/796 | ID: 1280.15892
Epoch 1/10 | Genome 124/796 | ID: 1280.26036
Epoch 1/10 | Genome 125/796 | ID: 1280.9336
Epoch 1/10 | Genome 126/796 | ID: 1280.9407
Epoch 1/10 | Genome 127/796 | ID: 1280.59617
Epoch 1/10 | Genome 128/796 | ID: 1280.59865
Epoch 1/10 | Genome 129/796 | ID: 1280.59348
Epoch 1/10 | Genome 130/796 | ID: 1280.51916
Checkpoint saved | Completed 130/796 genomes | Last genome: 0.05 min
Epoch 1/10 | Genome 131/796 | ID: 1280.59279
Epoch 1/10 | Genome 132/796 | ID: 1280.51777
Epoch 1/10 | Genome 133/796 | ID: 1280.59481
Epoch 1/10 | Genome 134/796 | ID: 1280.59522
Epoch 1/10 | Genome 135/796 | ID: 1280.26008
Epoch 1/10 | Genome 136/796 | ID: 1280.59359
Epoch 1/10 | Genome 137/796 | ID: 1280.59831
Epoch 1/10 | Genome 138/796 | ID: 1280.15921
Epoch 1/10 | Genome 139/796 | ID: 1280.59873
Epoch 1/10 | Genome 140/796 | ID: 1280.9253
Checkpoint saved | Completed 140/796 genomes | Last genome: 0.05 min
Epoch 1/10 | Genome 141/796 | ID: 1280.59307
Epoch 1/10 | Genome 142/796 | ID: 1280.9196
Epoch 1/10 | Genome 143/796 | ID: 1280.59277
Epoch 1/10 | Genome 144/796 | ID: 1280.26038
Epoch 1/10 | Genome 145/796 | ID: 1280.59405
Epoch 1/10 | Genome 146/796 | ID: 1280.59517
Epoch 1/10 | Genome 147/796 | ID: 1280.5982
Epoch 1/10 | Genome 148/796 | ID: 1280.15903
Epoch 1/10 | Genome 149/796 | ID: 1280.59396
Epoch 1/10 | Genome 150/796 | ID: 1280.59725
Checkpoint saved | Completed 150/796 genomes | Last genome: 0.05 min
Epoch 1/10 | Genome 151/796 | ID: 1280.51857
Epoch 1/10 | Genome 152/796 | ID: 1280.9359
Epoch 1/10 | Genome 153/796 | ID: 1280.9342
Epoch 1/10 | Genome 154/796 | ID: 1280.51927
Epoch 1/10 | Genome 155/796 | ID: 1280.59591
Epoch 1/10 | Genome 156/796 | ID: 1280.59847
Epoch 1/10 | Genome 157/796 | ID: 1280.51924
Epoch 1/10 | Genome 158/796 | ID: 1280.59642
Epoch 1/10 | Genome 159/796 | ID: 1280.59646
Epoch 1/10 | Genome 160/796 | ID: 1280.59723
Checkpoint saved | Completed 160/796 genomes | Last genome: 0.05 min
Epoch 1/10 | Genome 161/796 | ID: 1280.59599
Epoch 1/10 | Genome 162/796 | ID: 1280.59462
Epoch 1/10 | Genome 163/796 | ID: 1280.59337
Epoch 1/10 | Genome 164/796 | ID: 1280.9203
Epoch 1/10 | Genome 165/796 | ID: 1280.9195
Epoch 1/10 | Genome 166/796 | ID: 1280.59825
Epoch 1/10 | Genome 167/796 | ID: 1280.59484
Epoch 1/10 | Genome 168/796 | ID: 1280.51834
Epoch 1/10 | Genome 169/796 | ID: 1280.9254
Epoch 1/10 | Genome 170/796 | ID: 1280.9214
Checkpoint saved | Completed 170/796 genomes | Last genome: 0.05 min
Epoch 1/10 | Genome 171/796 | ID: 1280.59673
Epoch 1/10 | Genome 172/796 | ID: 1280.51875
Epoch 1/10 | Genome 173/796 | ID: 1280.26065
Epoch 1/10 | Genome 174/796 | ID: 1280.51903
Epoch 1/10 | Genome 175/796 | ID: 1280.15878
Epoch 1/10 | Genome 176/796 | ID: 1280.26046
Epoch 1/10 | Genome 177/796 | ID: 1280.26019
Epoch 1/10 | Genome 178/796 | ID: 1280.9316
Epoch 1/10 | Genome 179/796 | ID: 1280.59607
Epoch 1/10 | Genome 180/796 | ID: 1280.19784
Checkpoint saved | Completed 180/796 genomes | Last genome: 0.05 min
Epoch 1/10 | Genome 181/796 | ID: 1280.5941
Epoch 1/10 | Genome 182/796 | ID: 1280.26014
Epoch 1/10 | Genome 183/796 | ID: 1280.9229
Epoch 1/10 | Genome 184/796 | ID: 1280.59729
Epoch 1/10 | Genome 185/796 | ID: 1280.51769
Epoch 1/10 | Genome 186/796 | ID: 1280.5947
Epoch 1/10 | Genome 187/796 | ID: 1280.51872
Epoch 1/10 | Genome 188/796 | ID: 1280.9283
Epoch 1/10 | Genome 189/796 | ID: 1280.59351
Epoch 1/10 | Genome 190/796 | ID: 1280.9302
Checkpoint saved | Completed 190/796 genomes | Last genome: 0.05 min
Epoch 1/10 | Genome 191/796 | ID: 1280.15896
Epoch 1/10 | Genome 192/796 | ID: 1280.51886
Epoch 1/10 | Genome 193/796 | ID: 1280.9305
Epoch 1/10 | Genome 194/796 | ID: 1280.59431
Epoch 1/10 | Genome 195/796 | ID: 1280.59568
Epoch 1/10 | Genome 196/796 | ID: 1280.25998
Epoch 1/10 | Genome 197/796 | ID: 1280.51754
Epoch 1/10 | Genome 198/796 | ID: 1280.59885
Epoch 1/10 | Genome 199/796 | ID: 1280.9209
Epoch 1/10 | Genome 200/796 | ID: 1280.59395
Checkpoint saved | Completed 200/796 genomes | Last genome: 0.05 min
Epoch 1/10 | Genome 201/796 | ID: 1280.59295
Epoch 1/10 | Genome 202/796 | ID: 1280.59837
Epoch 1/10 | Genome 203/796 | ID: 1280.5983
Epoch 1/10 | Genome 204/796 | ID: 1280.59461
Epoch 1/10 | Genome 205/796 | ID: 1280.59543
Epoch 1/10 | Genome 206/796 | ID: 1280.26012
Epoch 1/10 | Genome 207/796 | ID: 1280.9348
Epoch 1/10 | Genome 208/796 | ID: 1280.59488
Epoch 1/10 | Genome 209/796 | ID: 1280.59876
Epoch 1/10 | Genome 210/796 | ID: 1280.59684
Checkpoint saved | Completed 210/796 genomes | Last genome: 0.05 min
Epoch 1/10 | Genome 211/796 | ID: 1280.59287
Epoch 1/10 | Genome 212/796 | ID: 1280.15908
Epoch 1/10 | Genome 213/796 | ID: 1280.51896
Epoch 1/10 | Genome 214/796 | ID: 1280.51906
Epoch 1/10 | Genome 215/796 | ID: 1280.59432
Epoch 1/10 | Genome 216/796 | ID: 1280.15912
Epoch 1/10 | Genome 217/796 | ID: 1280.59352
Epoch 1/10 | Genome 218/796 | ID: 1280.59539
Epoch 1/10 | Genome 219/796 | ID: 1280.16052
Epoch 1/10 | Genome 220/796 | ID: 1280.59468
Checkpoint saved | Completed 220/796 genomes | Last genome: 0.05 min
Epoch 1/10 | Genome 221/796 | ID: 1280.59908
Epoch 1/10 | Genome 222/796 | ID: 1280.51772
Epoch 1/10 | Genome 223/796 | ID: 1280.59311
Epoch 1/10 | Genome 224/796 | ID: 1280.51809
Epoch 1/10 | Genome 225/796 | ID: 1280.59819
Epoch 1/10 | Genome 226/796 | ID: 1280.7334
Epoch 1/10 | Genome 227/796 | ID: 1280.51789
Epoch 1/10 | Genome 228/796 | ID: 1280.9204
Epoch 1/10 | Genome 229/796 | ID: 1280.51823
Epoch 1/10 | Genome 230/796 | ID: 1280.9329
Checkpoint saved | Completed 230/796 genomes | Last genome: 0.06 min
Epoch 1/10 | Genome 231/796 | ID: 1280.51819
Epoch 1/10 | Genome 232/796 | ID: 1280.59612
Epoch 1/10 | Genome 233/796 | ID: 1280.59389
Epoch 1/10 | Genome 234/796 | ID: 1280.9218
Epoch 1/10 | Genome 235/796 | ID: 1280.59447
Epoch 1/10 | Genome 236/796 | ID: 1280.9224
Epoch 1/10 | Genome 237/796 | ID: 1280.59814
Epoch 1/10 | Genome 238/796 | ID: 1280.51915
Epoch 1/10 | Genome 239/796 | ID: 1280.9194
Epoch 1/10 | Genome 240/796 | ID: 1280.59509
Checkpoint saved | Completed 240/796 genomes | Last genome: 0.05 min
Epoch 1/10 | Genome 241/796 | ID: 1280.9193
Epoch 1/10 | Genome 242/796 | ID: 1280.5988
Epoch 1/10 | Genome 243/796 | ID: 1280.59895
Epoch 1/10 | Genome 244/796 | ID: 1280.59433
Epoch 1/10 | Genome 245/796 | ID: 1280.59866
Epoch 1/10 | Genome 246/796 | ID: 1280.59296
Epoch 1/10 | Genome 247/796 | ID: 1280.59708
Epoch 1/10 | Genome 248/796 | ID: 1280.59829
Epoch 1/10 | Genome 249/796 | ID: 1280.16763
Epoch 1/10 | Genome 250/796 | ID: 1280.59414
Checkpoint saved | Completed 250/796 genomes | Last genome: 0.05 min
Epoch 1/10 | Genome 251/796 | ID: 1280.51881
Epoch 1/10 | Genome 252/796 | ID: 1280.26032
Epoch 1/10 | Genome 253/796 | ID: 1280.59371
Epoch 1/10 | Genome 254/796 | ID: 1280.51848
Epoch 1/10 | Genome 255/796 | ID: 1280.51913
Epoch 1/10 | Genome 256/796 | ID: 1280.59402
Epoch 1/10 | Genome 257/796 | ID: 1280.9332
Epoch 1/10 | Genome 258/796 | ID: 1280.51867
Epoch 1/10 | Genome 259/796 | ID: 1280.51862
Epoch 1/10 | Genome 260/796 | ID: 1280.51805
Checkpoint saved | Completed 260/796 genomes | Last genome: 0.05 min
Epoch 1/10 | Genome 261/796 | ID: 1280.59441
Epoch 1/10 | Genome 262/796 | ID: 1280.59705
Epoch 1/10 | Genome 263/796 | ID: 1280.59553
Epoch 1/10 | Genome 264/796 | ID: 1280.51768
Epoch 1/10 | Genome 265/796 | ID: 1280.59438
Epoch 1/10 | Genome 266/796 | ID: 1280.59367
Epoch 1/10 | Genome 267/796 | ID: 1280.9308
Epoch 1/10 | Genome 268/796 | ID: 1280.59845
Epoch 1/10 | Genome 269/796 | ID: 1280.9222
Epoch 1/10 | Genome 270/796 | ID: 1280.59411
Checkpoint saved | Completed 270/796 genomes | Last genome: 0.05 min
Epoch 1/10 | Genome 271/796 | ID: 1280.59391
Epoch 1/10 | Genome 272/796 | ID: 1280.59758
Epoch 1/10 | Genome 273/796 | ID: 1280.26051
Epoch 1/10 | Genome 274/796 | ID: 1280.59632
Epoch 1/10 | Genome 275/796 | ID: 1280.5944
Epoch 1/10 | Genome 276/796 | ID: 1280.59254
Epoch 1/10 | Genome 277/796 | ID: 1280.59418
Epoch 1/10 | Genome 278/796 | ID: 1280.59528
Epoch 1/10 | Genome 279/796 | ID: 1280.51799
Epoch 1/10 | Genome 280/796 | ID: 1280.9256
Checkpoint saved | Completed 280/796 genomes | Last genome: 0.05 min
Epoch 1/10 | Genome 281/796 | ID: 1280.51763
Epoch 1/10 | Genome 282/796 | ID: 1280.51919
Epoch 1/10 | Genome 283/796 | ID: 1280.59324
Epoch 1/10 | Genome 284/796 | ID: 1280.59816
Epoch 1/10 | Genome 285/796 | ID: 1280.51928
Epoch 1/10 | Genome 286/796 | ID: 1280.59665
Epoch 1/10 | Genome 287/796 | ID: 1280.7343
Epoch 1/10 | Genome 288/796 | ID: 1280.25979
Epoch 1/10 | Genome 289/796 | ID: 1280.59773
Epoch 1/10 | Genome 290/796 | ID: 1280.26022
Checkpoint saved | Completed 290/796 genomes | Last genome: 0.05 min
Epoch 1/10 | Genome 291/796 | ID: 1280.51801
Epoch 1/10 | Genome 292/796 | ID: 1280.9247
Epoch 1/10 | Genome 293/796 | ID: 1280.51852
Epoch 1/10 | Genome 294/796 | ID: 1280.7372
Epoch 1/10 | Genome 295/796 | ID: 1280.15868
Epoch 1/10 | Genome 296/796 | ID: 1280.59408
Epoch 1/10 | Genome 297/796 | ID: 1280.26002
Epoch 1/10 | Genome 298/796 | ID: 1280.59419
Epoch 1/10 | Genome 299/796 | ID: 1280.59424
Epoch 1/10 | Genome 300/796 | ID: 1280.59398
Checkpoint saved | Completed 300/796 genomes | Last genome: 0.05 min
Epoch 1/10 | Genome 301/796 | ID: 1280.9191
Epoch 1/10 | Genome 302/796 | ID: 1280.59467
Epoch 1/10 | Genome 303/796 | ID: 1280.15922
Epoch 1/10 | Genome 304/796 | ID: 1280.59874
Epoch 1/10 | Genome 305/796 | ID: 1280.51874
Epoch 1/10 | Genome 306/796 | ID: 1280.51753
Epoch 1/10 | Genome 307/796 | ID: 1280.59282
Epoch 1/10 | Genome 308/796 | ID: 1280.59297
Epoch 1/10 | Genome 309/796 | ID: 1280.51749
Epoch 1/10 | Genome 310/796 | ID: 1280.59752
Checkpoint saved | Completed 310/796 genomes | Last genome: 0.05 min
Epoch 1/10 | Genome 311/796 | ID: 1280.59344
Epoch 1/10 | Genome 312/796 | ID: 1280.51937
Epoch 1/10 | Genome 313/796 | ID: 1280.59275
Epoch 1/10 | Genome 314/796 | ID: 1280.59369
Epoch 1/10 | Genome 315/796 | ID: 1280.5928
Epoch 1/10 | Genome 316/796 | ID: 1280.9226
Epoch 1/10 | Genome 317/796 | ID: 1280.26055
Epoch 1/10 | Genome 318/796 | ID: 1280.59789
Epoch 1/10 | Genome 319/796 | ID: 1280.59477
Epoch 1/10 | Genome 320/796 | ID: 1280.59487
Checkpoint saved | Completed 320/796 genomes | Last genome: 0.05 min
Epoch 1/10 | Genome 321/796 | ID: 1280.26067
Epoch 1/10 | Genome 322/796 | ID: 1280.25999
Epoch 1/10 | Genome 323/796 | ID: 1280.59571
Epoch 1/10 | Genome 324/796 | ID: 1280.51853
Epoch 1/10 | Genome 325/796 | ID: 1280.59754
Epoch 1/10 | Genome 326/796 | ID: 1280.15902
Epoch 1/10 | Genome 327/796 | ID: 1280.51904
Epoch 1/10 | Genome 328/796 | ID: 1280.59362
Epoch 1/10 | Genome 329/796 | ID: 1280.59648
Epoch 1/10 | Genome 330/796 | ID: 1280.59747
Checkpoint saved | Completed 330/796 genomes | Last genome: 0.05 min
Epoch 1/10 | Genome 331/796 | ID: 1280.9227
Epoch 1/10 | Genome 332/796 | ID: 1280.59806
Epoch 1/10 | Genome 333/796 | ID: 1280.9344
Epoch 1/10 | Genome 334/796 | ID: 1280.51843
Epoch 1/10 | Genome 335/796 | ID: 1280.59388
Epoch 1/10 | Genome 336/796 | ID: 1280.59288
Epoch 1/10 | Genome 337/796 | ID: 1280.59475
Epoch 1/10 | Genome 338/796 | ID: 1280.5966
Epoch 1/10 | Genome 339/796 | ID: 1280.51909
Epoch 1/10 | Genome 340/796 | ID: 1280.59771
Checkpoint saved | Completed 340/796 genomes | Last genome: 0.05 min
Epoch 1/10 | Genome 341/796 | ID: 1280.59416
Epoch 1/10 | Genome 342/796 | ID: 1280.9231
Epoch 1/10 | Genome 343/796 | ID: 1280.59889
Epoch 1/10 | Genome 344/796 | ID: 1280.5972
Epoch 1/10 | Genome 345/796 | ID: 1280.59575
Epoch 1/10 | Genome 346/796 | ID: 1280.59537
Epoch 1/10 | Genome 347/796 | ID: 1280.59626
Epoch 1/10 | Genome 348/796 | ID: 1280.59523
Epoch 1/10 | Genome 349/796 | ID: 1280.59377
Epoch 1/10 | Genome 350/796 | ID: 1280.5957
Checkpoint saved | Completed 350/796 genomes | Last genome: 0.05 min
Epoch 1/10 | Genome 351/796 | ID: 1280.9333
Epoch 1/10 | Genome 352/796 | ID: 1280.51931
Epoch 1/10 | Genome 353/796 | ID: 1280.5925
Epoch 1/10 | Genome 354/796 | ID: 1280.51791
Epoch 1/10 | Genome 355/796 | ID: 1280.15874
Epoch 1/10 | Genome 356/796 | ID: 1280.26029
Epoch 1/10 | Genome 357/796 | ID: 1280.7373
Epoch 1/10 | Genome 358/796 | ID: 1280.51893
Epoch 1/10 | Genome 359/796 | ID: 1280.5977
Epoch 1/10 | Genome 360/796 | ID: 1280.51934
Checkpoint saved | Completed 360/796 genomes | Last genome: 0.05 min
Epoch 1/10 | Genome 361/796 | ID: 1280.59248
Epoch 1/10 | Genome 362/796 | ID: 1280.51866
Epoch 1/10 | Genome 363/796 | ID: 1280.9282
Epoch 1/10 | Genome 364/796 | ID: 1280.59346
Epoch 1/10 | Genome 365/796 | ID: 1280.9265
Epoch 1/10 | Genome 366/796 | ID: 1280.51932
Epoch 1/10 | Genome 367/796 | ID: 1280.15867
Epoch 1/10 | Genome 368/796 | ID: 1280.26068
Epoch 1/10 | Genome 369/796 | ID: 1280.51796
Epoch 1/10 | Genome 370/796 | ID: 1280.59363
Checkpoint saved | Completed 370/796 genomes | Last genome: 0.05 min
Epoch 1/10 | Genome 371/796 | ID: 1280.9368
Epoch 1/10 | Genome 372/796 | ID: 1280.9287
Epoch 1/10 | Genome 373/796 | ID: 1280.59483
Epoch 1/10 | Genome 374/796 | ID: 1280.59822
Epoch 1/10 | Genome 375/796 | ID: 1280.25996
Epoch 1/10 | Genome 376/796 | ID: 1280.51844
Epoch 1/10 | Genome 377/796 | ID: 1280.59584
Epoch 1/10 | Genome 378/796 | ID: 1280.59669
Epoch 1/10 | Genome 379/796 | ID: 1280.59899
Epoch 1/10 | Genome 380/796 | ID: 1280.59328
Checkpoint saved | Completed 380/796 genomes | Last genome: 0.05 min
Epoch 1/10 | Genome 381/796 | ID: 1280.9376
Epoch 1/10 | Genome 382/796 | ID: 1280.51929
Epoch 1/10 | Genome 383/796 | ID: 1280.15884
Epoch 1/10 | Genome 384/796 | ID: 1280.59566
Epoch 1/10 | Genome 385/796 | ID: 1280.59588

In [74]:

import torch
from pathlib import Path

checkpoint_path = Path(
    "/kaggle/working/models/latest_amr_genome_cnn.pt"
)

checkpoint = torch.load(
    checkpoint_path,
    map_location="cpu",
    weights_only=False
)

print("Saved epoch:", checkpoint.get("epoch"))
print("Next genome index:", checkpoint.get("next_train_index"))
print("Epoch complete:", checkpoint.get("epoch_complete"))
print("Saved training losses:", len(checkpoint.get("train_losses", [])))
print("History entries:", len(checkpoint.get("history", [])))

Saved epoch: 10
Next genome index: 590
Epoch complete: False
Saved training losses: 590
History entries: 9

In [75]:

print("Saved epoch:", checkpoint["epoch"])
print("Next index:", checkpoint["next_train_index"])
print("Shuffled genome IDs:", len(checkpoint["shuffled_ids"]))
print("Training losses:", len(checkpoint["train_losses"]))
print("Epoch complete:", checkpoint["epoch_complete"])
print("History epochs:", [item["epoch"] for item in checkpoint["history"]])

Saved epoch: 10
Next index: 590
Shuffled genome IDs: 796
Training losses: 590
Epoch complete: False
History epochs: [1, 2, 3, 4, 5, 6, 7, 8, 9]

In [76]:

required = [
    "model",
    "optimizer",
    "forward_genome",
    "train_genome_ids",
    "val_genome_ids",
    "criterion",
    "WINDOW_BATCH_SIZE",
    "device",
    "SEED"
]

for name in required:
    print(f"{name}: {'available' if name in globals() else 'MISSING'}")

model: available
optimizer: available
forward_genome: available
train_genome_ids: available
val_genome_ids: available
criterion: available
WINDOW_BATCH_SIZE: available
device: available
SEED: available

In [77]:

print("Optimizer state:", "optimizer_state_dict" in checkpoint)
print("Model state:", "model_state_dict" in checkpoint)
print("Saved genome order:", "shuffled_ids" in checkpoint)
print("Saved next index:", checkpoint.get("next_train_index"))
print("Saved loss count:", len(checkpoint.get("train_losses", [])))

Optimizer state: True
Model state: True
Saved genome order: True
Saved next index: 590
Saved loss count: 590

In [78]:

# Recovery — Resume interrupted Epoch 10

import gc
import time
import numpy as np
import pandas as pd
import torch
from pathlib import Path
from sklearn.metrics import accuracy_score, roc_auc_score

CHECKPOINT_PATH = Path("/kaggle/working/models/latest_amr_genome_cnn.pt")
BEST_MODEL_PATH = Path("/kaggle/working/models/best_amr_genome_cnn.pt")
TEMP_PATH = Path("/kaggle/working/models/latest_amr_genome_cnn.tmp")

assert CHECKPOINT_PATH.exists(), "Latest checkpoint is missing."

# Load checkpoint without modifying the original file
ckpt = torch.load(
    CHECKPOINT_PATH,
    map_location=device,
    weights_only=False
)

assert ckpt["epoch"] == 10, f"Expected epoch 10, found {ckpt['epoch']}."
assert ckpt["epoch_complete"] is False, "This epoch is already marked complete."

model.load_state_dict(ckpt["model_state_dict"])
optimizer.load_state_dict(ckpt["optimizer_state_dict"])

epoch = ckpt["epoch"]
start_index = ckpt["next_train_index"]
shuffled_ids = ckpt["shuffled_ids"]
train_losses = ckpt["train_losses"]
history = ckpt["history"]
best_val_loss = ckpt.get("best_val_loss", float("inf"))

assert len(shuffled_ids) == len(train_genome_ids), "Training genome count mismatch."
assert 0 < start_index < len(shuffled_ids), "Unexpected resume index."
assert len(train_losses) == start_index, "Saved loss count and index disagree."

print(f"Resuming Epoch {epoch} at saved index {start_index}.")
print(f"Already processed: {start_index}/{len(shuffled_ids)}")
print(f"Remaining: {len(shuffled_ids) - start_index}")

def save_recovery_checkpoint(next_index, complete=False):
    data = {
        "epoch": epoch,
        "next_train_index": next_index,
        "shuffled_ids": shuffled_ids,
        "train_losses": train_losses,
        "epoch_complete": complete,
        "model_state_dict": model.state_dict(),
        "optimizer_state_dict": optimizer.state_dict(),
        "best_val_loss": best_val_loss,
        "history": history,
        "seed": SEED
    }
    torch.save(data, TEMP_PATH)
    TEMP_PATH.replace(CHECKPOINT_PATH)

# Continue from the saved index
model.train()

for index in range(start_index, len(shuffled_ids)):
    genome_id = shuffled_ids[index]
    genome_start = time.time()

    print(
        f"Epoch 10/10 | Genome {index + 1}/{len(shuffled_ids)} "
        f"| ID: {genome_id}",
        flush=True
    )

    optimizer.zero_grad(set_to_none=True)

    genome_embedding, attention_weights, logit, label = forward_genome(
        model,
        genome_id,
        batch_size=WINDOW_BATCH_SIZE,
        device=device
    )

    target = torch.tensor(
        float(label), dtype=torch.float32, device=device
    )
    loss = criterion(logit.reshape(()), target)
    loss.backward()
    optimizer.step()

    train_losses.append(loss.item())

    del genome_embedding, attention_weights, logit, target, loss

    # Save progress every 10 genomes
    if (index + 1) % 10 == 0 or index == len(shuffled_ids) - 1:
        save_recovery_checkpoint(index + 1)
        print(
            f"Checkpoint saved: {index + 1}/{len(shuffled_ids)} "
            f"| Last genome: {(time.time() - genome_start) / 60:.2f} min",
            flush=True
        )

    gc.collect()

# Compute training loss for the complete epoch
train_loss = float(np.mean(train_losses))

# Run validation
model.eval()
val_losses, val_labels, val_probs = [], [], []

with torch.no_grad():
    for i, genome_id in enumerate(val_genome_ids, start=1):
        print(f"Validation {i}/{len(val_genome_ids)}", flush=True)

        genome_embedding, attention_weights, logit, label = forward_genome(
            model,
            genome_id,
            batch_size=WINDOW_BATCH_SIZE,
            device=device
        )

        target = torch.tensor(
            float(label), dtype=torch.float32, device=device
        )

        val_losses.append(
            criterion(logit.reshape(()), target).item()
        )
        val_labels.append(int(label))
        val_probs.append(torch.sigmoid(logit).item())

        del genome_embedding, attention_weights, logit, target

val_loss = float(np.mean(val_losses))
val_predictions = [int(p >= 0.5) for p in val_probs]
val_accuracy = accuracy_score(val_labels, val_predictions)
val_auc = (
    roc_auc_score(val_labels, val_probs)
    if len(set(val_labels)) == 2 else float("nan")
)

result = {
    "epoch": 10,
    "train_loss": train_loss,
    "val_loss": val_loss,
    "val_accuracy": val_accuracy,
    "val_auc": val_auc
}
history.append(result)

print("\nEpoch 10/10 complete")
print(f"Training loss:       {train_loss:.4f}")
print(f"Validation loss:     {val_loss:.4f}")
print(f"Validation accuracy: {val_accuracy:.4f}")
print(f"Validation ROC-AUC:  {val_auc:.4f}")

# Update best model only if validation loss improves
if val_loss < best_val_loss:
    best_val_loss = val_loss
    torch.save({
        "epoch": 10,
        "model_state_dict": model.state_dict(),
        "optimizer_state_dict": optimizer.state_dict(),
        "train_loss": train_loss,
        "val_loss": val_loss,
        "val_accuracy": val_accuracy,
        "val_auc": val_auc,
        "history": history,
        "seed": SEED
    }, BEST_MODEL_PATH)
    print("Best model checkpoint updated.")

# Save final checkpoint, marked complete
save_recovery_checkpoint(len(shuffled_ids), complete=True)

print("\nRecovery finished.")
print("Best model:", BEST_MODEL_PATH)
print("Latest checkpoint:", CHECKPOINT_PATH)
display(pd.DataFrame(history))

Resuming Epoch 10 at saved index 590.
Already processed: 590/796
Remaining: 206
Epoch 10/10 | Genome 591/796 | ID: 1280.26038
Epoch 10/10 | Genome 592/796 | ID: 1280.59616
Epoch 10/10 | Genome 593/796 | ID: 1280.26045
Epoch 10/10 | Genome 594/796 | ID: 1280.51815
Epoch 10/10 | Genome 595/796 | ID: 1280.59308
Epoch 10/10 | Genome 596/796 | ID: 1280.9274
Epoch 10/10 | Genome 597/796 | ID: 1280.59258
Epoch 10/10 | Genome 598/796 | ID: 1280.9297
Epoch 10/10 | Genome 599/796 | ID: 1280.9268
Epoch 10/10 | Genome 600/796 | ID: 1280.59287
Checkpoint saved: 600/796 | Last genome: 0.05 min
Epoch 10/10 | Genome 601/796 | ID: 1280.59682
Epoch 10/10 | Genome 602/796 | ID: 1280.59732
Epoch 10/10 | Genome 603/796 | ID: 1280.25996
Epoch 10/10 | Genome 604/796 | ID: 1280.51823
Epoch 10/10 | Genome 605/796 | ID: 1280.59254
Epoch 10/10 | Genome 606/796 | ID: 1280.9403
Epoch 10/10 | Genome 607/796 | ID: 1280.59536
Epoch 10/10 | Genome 608/796 | ID: 1280.51814
Epoch 10/10 | Genome 609/796 | ID: 1280.26049
Epoch 10/10 | Genome 610/796 | ID: 1280.59669
Checkpoint saved: 610/796 | Last genome: 0.05 min
Epoch 10/10 | Genome 611/796 | ID: 1280.59507
Epoch 10/10 | Genome 612/796 | ID: 1280.59798
Epoch 10/10 | Genome 613/796 | ID: 1280.59727
Epoch 10/10 | Genome 614/796 | ID: 1280.26063
Epoch 10/10 | Genome 615/796 | ID: 1280.51767
Epoch 10/10 | Genome 616/796 | ID: 1280.59905
Epoch 10/10 | Genome 617/796 | ID: 1280.51776
Epoch 10/10 | Genome 618/796 | ID: 1280.9269
Epoch 10/10 | Genome 619/796 | ID: 1280.59654
Epoch 10/10 | Genome 620/796 | ID: 1280.59753
Checkpoint saved: 620/796 | Last genome: 0.05 min
Epoch 10/10 | Genome 621/796 | ID: 1280.59351
Epoch 10/10 | Genome 622/796 | ID: 1280.9377
Epoch 10/10 | Genome 623/796 | ID: 1280.59806
Epoch 10/10 | Genome 624/796 | ID: 1280.5974
Epoch 10/10 | Genome 625/796 | ID: 1280.59646
Epoch 10/10 | Genome 626/796 | ID: 1280.15928
Epoch 10/10 | Genome 627/796 | ID: 1280.15889
Epoch 10/10 | Genome 628/796 | ID: 1280.9295
Epoch 10/10 | Genome 629/796 | ID: 1280.51924
Epoch 10/10 | Genome 630/796 | ID: 1280.9338
Checkpoint saved: 630/796 | Last genome: 0.05 min
Epoch 10/10 | Genome 631/796 | ID: 1280.9226
Epoch 10/10 | Genome 632/796 | ID: 1280.59553
Epoch 10/10 | Genome 633/796 | ID: 1280.59504
Epoch 10/10 | Genome 634/796 | ID: 1280.59899
Epoch 10/10 | Genome 635/796 | ID: 1280.59297
Epoch 10/10 | Genome 636/796 | ID: 1280.59685
Epoch 10/10 | Genome 637/796 | ID: 1280.59466
Epoch 10/10 | Genome 638/796 | ID: 1280.59707
Epoch 10/10 | Genome 639/796 | ID: 1280.59448
Epoch 10/10 | Genome 640/796 | ID: 1280.59544
Checkpoint saved: 640/796 | Last genome: 0.05 min
Epoch 10/10 | Genome 641/796 | ID: 1280.59431
Epoch 10/10 | Genome 642/796 | ID: 1280.59723
Epoch 10/10 | Genome 643/796 | ID: 1280.25982
Epoch 10/10 | Genome 644/796 | ID: 1280.59844
Epoch 10/10 | Genome 645/796 | ID: 1280.59533
Epoch 10/10 | Genome 646/796 | ID: 1280.9254
Epoch 10/10 | Genome 647/796 | ID: 1280.9225
Epoch 10/10 | Genome 648/796 | ID: 1280.26029
Epoch 10/10 | Genome 649/796 | ID: 1280.25983
Epoch 10/10 | Genome 650/796 | ID: 1280.59831
Checkpoint saved: 650/796 | Last genome: 0.05 min
Epoch 10/10 | Genome 651/796 | ID: 1280.59307
Epoch 10/10 | Genome 652/796 | ID: 1280.59737
Epoch 10/10 | Genome 653/796 | ID: 1280.59895
Epoch 10/10 | Genome 654/796 | ID: 1280.15885
Epoch 10/10 | Genome 655/796 | ID: 1280.7372
Epoch 10/10 | Genome 656/796 | ID: 1280.15906
Epoch 10/10 | Genome 657/796 | ID: 1280.5955
Epoch 10/10 | Genome 658/796 | ID: 1280.59841
Epoch 10/10 | Genome 659/796 | ID: 1280.51839
Epoch 10/10 | Genome 660/796 | ID: 1280.9332
Checkpoint saved: 660/796 | Last genome: 0.05 min
Epoch 10/10 | Genome 661/796 | ID: 1280.51859
Epoch 10/10 | Genome 662/796 | ID: 1280.59489
Epoch 10/10 | Genome 663/796 | ID: 1280.9376
Epoch 10/10 | Genome 664/796 | ID: 1280.26057
Epoch 10/10 | Genome 665/796 | ID: 1280.16436
Epoch 10/10 | Genome 666/796 | ID: 1280.59897
Epoch 10/10 | Genome 667/796 | ID: 1280.59585
Epoch 10/10 | Genome 668/796 | ID: 1280.59328
Epoch 10/10 | Genome 669/796 | ID: 1280.9249
Epoch 10/10 | Genome 670/796 | ID: 1280.9256
Checkpoint saved: 670/796 | Last genome: 0.05 min
Epoch 10/10 | Genome 671/796 | ID: 1280.9373
Epoch 10/10 | Genome 672/796 | ID: 1280.59517
Epoch 10/10 | Genome 673/796 | ID: 1280.7356
Epoch 10/10 | Genome 674/796 | ID: 1280.9279
Epoch 10/10 | Genome 675/796 | ID: 1280.59881
Epoch 10/10 | Genome 676/796 | ID: 1280.59316
Epoch 10/10 | Genome 677/796 | ID: 1280.7334
Epoch 10/10 | Genome 678/796 | ID: 1280.5979
Epoch 10/10 | Genome 679/796 | ID: 1280.59796
Epoch 10/10 | Genome 680/796 | ID: 1280.5927
Checkpoint saved: 680/796 | Last genome: 0.05 min
Epoch 10/10 | Genome 681/796 | ID: 1280.59752
Epoch 10/10 | Genome 682/796 | ID: 1280.59333
Epoch 10/10 | Genome 683/796 | ID: 1280.59362
Epoch 10/10 | Genome 684/796 | ID: 1280.15878
Epoch 10/10 | Genome 685/796 | ID: 1280.59523
Epoch 10/10 | Genome 686/796 | ID: 1280.59619
Epoch 10/10 | Genome 687/796 | ID: 1280.51863
Epoch 10/10 | Genome 688/796 | ID: 1280.51933
Epoch 10/10 | Genome 689/796 | ID: 1280.59893
Epoch 10/10 | Genome 690/796 | ID: 1280.9204
Checkpoint saved: 690/796 | Last genome: 0.05 min
Epoch 10/10 | Genome 691/796 | ID: 1280.51791
Epoch 10/10 | Genome 692/796 | ID: 1280.15927
Epoch 10/10 | Genome 693/796 | ID: 1280.59741
Epoch 10/10 | Genome 694/796 | ID: 1280.9326
Epoch 10/10 | Genome 695/796 | ID: 1280.5947
Epoch 10/10 | Genome 696/796 | ID: 1280.51906
Epoch 10/10 | Genome 697/796 | ID: 1280.9283
Epoch 10/10 | Genome 698/796 | ID: 1280.59495
Epoch 10/10 | Genome 699/796 | ID: 1280.59571
Epoch 10/10 | Genome 700/796 | ID: 1280.59756
Checkpoint saved: 700/796 | Last genome: 0.05 min
Epoch 10/10 | Genome 701/796 | ID: 1280.51844
Epoch 10/10 | Genome 702/796 | ID: 1280.59609
Epoch 10/10 | Genome 703/796 | ID: 1280.51834
Epoch 10/10 | Genome 704/796 | ID: 1280.59653
Epoch 10/10 | Genome 705/796 | ID: 1280.59724
Epoch 10/10 | Genome 706/796 | ID: 1280.9372
Epoch 10/10 | Genome 707/796 | ID: 1280.5949
Epoch 10/10 | Genome 708/796 | ID: 1280.59662
Epoch 10/10 | Genome 709/796 | ID: 1280.15877
Epoch 10/10 | Genome 710/796 | ID: 1280.51799
Checkpoint saved: 710/796 | Last genome: 0.05 min
Epoch 10/10 | Genome 711/796 | ID: 1280.26021
Epoch 10/10 | Genome 712/796 | ID: 1280.59622
Epoch 10/10 | Genome 713/796 | ID: 1280.26067
Epoch 10/10 | Genome 714/796 | ID: 1280.59449
Epoch 10/10 | Genome 715/796 | ID: 1280.9346
Epoch 10/10 | Genome 716/796 | ID: 1280.9239
Epoch 10/10 | Genome 717/796 | ID: 1280.59909
Epoch 10/10 | Genome 718/796 | ID: 1280.9289
Epoch 10/10 | Genome 719/796 | ID: 1280.51874
Epoch 10/10 | Genome 720/796 | ID: 1280.51884
Checkpoint saved: 720/796 | Last genome: 0.05 min
Epoch 10/10 | Genome 721/796 | ID: 1280.9368
Epoch 10/10 | Genome 722/796 | ID: 1280.9219
Epoch 10/10 | Genome 723/796 | ID: 1280.59393
Epoch 10/10 | Genome 724/796 | ID: 1280.59568
Epoch 10/10 | Genome 725/796 | ID: 1280.59751
Epoch 10/10 | Genome 726/796 | ID: 1280.26041
Epoch 10/10 | Genome 727/796 | ID: 1280.25976
Epoch 10/10 | Genome 728/796 | ID: 1280.59439
Epoch 10/10 | Genome 729/796 | ID: 1280.51927
Epoch 10/10 | Genome 730/796 | ID: 1280.5928
Checkpoint saved: 730/796 | Last genome: 0.05 min
Epoch 10/10 | Genome 731/796 | ID: 1280.51769
Epoch 10/10 | Genome 732/796 | ID: 1280.51886
Epoch 10/10 | Genome 733/796 | ID: 1280.51805
Epoch 10/10 | Genome 734/796 | ID: 1280.59401
Epoch 10/10 | Genome 735/796 | ID: 1280.59802
Epoch 10/10 | Genome 736/796 | ID: 1280.51909
Epoch 10/10 | Genome 737/796 | ID: 1280.59657
Epoch 10/10 | Genome 738/796 | ID: 1280.59389
Epoch 10/10 | Genome 739/796 | ID: 1280.59337
Epoch 10/10 | Genome 740/796 | ID: 1280.59506
Checkpoint saved: 740/796 | Last genome: 0.05 min
Epoch 10/10 | Genome 741/796 | ID: 1280.51912
Epoch 10/10 | Genome 742/796 | ID: 1280.9379
Epoch 10/10 | Genome 743/796 | ID: 1280.9196
Epoch 10/10 | Genome 744/796 | ID: 1280.9236
Epoch 10/10 | Genome 745/796 | ID: 1280.51898
Epoch 10/10 | Genome 746/796 | ID: 1280.59398
Epoch 10/10 | Genome 747/796 | ID: 1280.59346
Epoch 10/10 | Genome 748/796 | ID: 1280.26051
Epoch 10/10 | Genome 749/796 | ID: 1280.26008
Epoch 10/10 | Genome 750/796 | ID: 1280.9345
Checkpoint saved: 750/796 | Last genome: 0.05 min
Epoch 10/10 | Genome 751/796 | ID: 1280.59907
Epoch 10/10 | Genome 752/796 | ID: 1280.59371
Epoch 10/10 | Genome 753/796 | ID: 1280.9358
Epoch 10/10 | Genome 754/796 | ID: 1280.59245
Epoch 10/10 | Genome 755/796 | ID: 1280.15875
Epoch 10/10 | Genome 756/796 | ID: 1280.9222
Epoch 10/10 | Genome 757/796 | ID: 1280.51831
Epoch 10/10 | Genome 758/796 | ID: 1280.9276
Epoch 10/10 | Genome 759/796 | ID: 1280.51913
Epoch 10/10 | Genome 760/796 | ID: 1280.51817
Checkpoint saved: 760/796 | Last genome: 0.05 min
Epoch 10/10 | Genome 761/796 | ID: 1280.9336
Epoch 10/10 | Genome 762/796 | ID: 1280.59664
Epoch 10/10 | Genome 763/796 | ID: 1280.51795
Epoch 10/10 | Genome 764/796 | ID: 1280.59477
Epoch 10/10 | Genome 765/796 | ID: 1280.59468
Epoch 10/10 | Genome 766/796 | ID: 1280.59601
Epoch 10/10 | Genome 767/796 | ID: 1280.59791
Epoch 10/10 | Genome 768/796 | ID: 1280.5926
Epoch 10/10 | Genome 769/796 | ID: 1280.51852
Epoch 10/10 | Genome 770/796 | ID: 1280.59288
Checkpoint saved: 770/796 | Last genome: 0.05 min
Epoch 10/10 | Genome 771/796 | ID: 1280.59313
Epoch 10/10 | Genome 772/796 | ID: 1280.9299
Epoch 10/10 | Genome 773/796 | ID: 1280.59338
Epoch 10/10 | Genome 774/796 | ID: 1280.59561
Epoch 10/10 | Genome 775/796 | ID: 1280.59865
Epoch 10/10 | Genome 776/796 | ID: 1280.59277
Epoch 10/10 | Genome 777/796 | ID: 1280.59769
Epoch 10/10 | Genome 778/796 | ID: 1280.59714
Epoch 10/10 | Genome 779/796 | ID: 1280.9335
Epoch 10/10 | Genome 780/796 | ID: 1280.59381
Checkpoint saved: 780/796 | Last genome: 0.05 min
Epoch 10/10 | Genome 781/796 | ID: 1280.59665
Epoch 10/10 | Genome 782/796 | ID: 1280.59484
Epoch 10/10 | Genome 783/796 | ID: 1280.59419
Epoch 10/10 | Genome 784/796 | ID: 1280.25992
Epoch 10/10 | Genome 785/796 | ID: 1280.26032
Epoch 10/10 | Genome 786/796 | ID: 1280.9227
Epoch 10/10 | Genome 787/796 | ID: 1280.59347
Epoch 10/10 | Genome 788/796 | ID: 1280.59549
Epoch 10/10 | Genome 789/796 | ID: 1280.59575
Epoch 10/10 | Genome 790/796 | ID: 1280.59846
Checkpoint saved: 790/796 | Last genome: 0.05 min
Epoch 10/10 | Genome 791/796 | ID: 1280.9197
Epoch 10/10 | Genome 792/796 | ID: 1280.59357
Epoch 10/10 | Genome 793/796 | ID: 1280.59815
Epoch 10/10 | Genome 794/796 | ID: 1280.59462
Epoch 10/10 | Genome 795/796 | ID: 1280.59486
Epoch 10/10 | Genome 796/796 | ID: 1280.59693
Checkpoint saved: 796/796 | Last genome: 0.05 min
Validation 1/171
Validation 2/171
Validation 3/171
Validation 4/171
Validation 5/171
Validation 6/171
Validation 7/171
Validation 8/171
Validation 9/171
Validation 10/171
Validation 11/171
Validation 12/171
Validation 13/171
Validation 14/171
Validation 15/171
Validation 16/171
Validation 17/171
Validation 18/171
Validation 19/171
Validation 20/171
Validation 21/171
Validation 22/171
Validation 23/171
Validation 24/171
Validation 25/171
Validation 26/171
Validation 27/171
Validation 28/171
Validation 29/171
Validation 30/171
Validation 31/171
Validation 32/171
Validation 33/171
Validation 34/171
Validation 35/171
Validation 36/171
Validation 37/171
Validation 38/171
Validation 39/171
Validation 40/171
Validation 41/171
Validation 42/171
Validation 43/171
Validation 44/171
Validation 45/171
Validation 46/171
Validation 47/171
Validation 48/171
Validation 49/171
Validation 50/171
Validation 51/171
Validation 52/171
Validation 53/171
Validation 54/171
Validation 55/171
Validation 56/171
Validation 57/171
Validation 58/171
Validation 59/171
Validation 60/171
Validation 61/171
Validation 62/171
Validation 63/171
Validation 64/171
Validation 65/171
Validation 66/171
Validation 67/171
Validation 68/171
Validation 69/171
Validation 70/171
Validation 71/171
Validation 72/171
Validation 73/171
Validation 74/171
Validation 75/171
Validation 76/171
Validation 77/171
Validation 78/171
Validation 79/171
Validation 80/171
Validation 81/171
Validation 82/171
Validation 83/171
Validation 84/171
Validation 85/171
Validation 86/171
Validation 87/171
Validation 88/171
Validation 89/171
Validation 90/171
Validation 91/171
Validation 92/171
Validation 93/171
Validation 94/171
Validation 95/171
Validation 96/171
Validation 97/171
Validation 98/171
Validation 99/171
Validation 100/171
Validation 101/171
Validation 102/171
Validation 103/171
Validation 104/171
Validation 105/171
Validation 106/171
Validation 107/171
Validation 108/171
Validation 109/171
Validation 110/171
Validation 111/171
Validation 112/171
Validation 113/171
Validation 114/171
Validation 115/171
Validation 116/171
Validation 117/171
Validation 118/171
Validation 119/171
Validation 120/171
Validation 121/171
Validation 122/171
Validation 123/171
Validation 124/171
Validation 125/171
Validation 126/171
Validation 127/171
Validation 128/171
Validation 129/171
Validation 130/171
Validation 131/171
Validation 132/171
Validation 133/171
Validation 134/171
Validation 135/171
Validation 136/171
Validation 137/171
Validation 138/171
Validation 139/171
Validation 140/171
Validation 141/171
Validation 142/171
Validation 143/171
Validation 144/171
Validation 145/171
Validation 146/171
Validation 147/171
Validation 148/171
Validation 149/171
Validation 150/171
Validation 151/171
Validation 152/171
Validation 153/171
Validation 154/171
Validation 155/171
Validation 156/171
Validation 157/171
Validation 158/171
Validation 159/171
Validation 160/171
Validation 161/171
Validation 162/171
Validation 163/171
Validation 164/171
Validation 165/171
Validation 166/171
Validation 167/171
Validation 168/171
Validation 169/171
Validation 170/171
Validation 171/171

Epoch 10/10 complete
Training loss:       0.6803
Validation loss:     0.6794
Validation accuracy: 0.5848
Validation ROC-AUC:  0.7271

Recovery finished.
Best model: /kaggle/working/models/best_amr_genome_cnn.pt
Latest checkpoint: /kaggle/working/models/latest_amr_genome_cnn.pt

   epoch  train_loss  val_loss  val_accuracy   val_auc
0      1    0.685776  0.679562      0.584795  0.682887
1      2    0.682257  0.678730      0.584795  0.788521
2      3    0.682012  0.679635      0.584795  0.802606
3      4    0.691991  0.678764      0.584795  0.662676
4      5    0.681978  0.678748      0.584795  0.665141
5      6    0.680994  0.678717      0.584795  0.671197
6      7    0.681034  0.678920      0.584795  0.687183
7      8    0.680876  0.678787      0.584795  0.707958
8      9    0.680851  0.678913      0.584795  0.721549
9     10    0.680338  0.679441      0.584795  0.727113

In [79]:
from pathlib import Path
import torch

best_path = Path("/kaggle/working/models/best_amr_genome_cnn.pt")
latest_path = Path("/kaggle/working/models/latest_amr_genome_cnn.pt")

print("Best checkpoint exists:", best_path.exists())
print("Latest checkpoint exists:", latest_path.exists())
print("Model in memory:", "model" in globals())
print("Test IDs in memory:", "test_genome_ids" in globals())
print("Evaluation function available:", "forward_genome" in globals())

Best checkpoint exists: True
Latest checkpoint exists: True
Model in memory: True
Test IDs in memory: True
Evaluation function available: True

In [80]:
import torch
from pathlib import Path

BEST_MODEL_PATH = Path("/kaggle/working/models/best_amr_genome_cnn.pt")

checkpoint = torch.load(
    BEST_MODEL_PATH,
    map_location=device,
    weights_only=False
)

model.load_state_dict(checkpoint["model_state_dict"])
model.eval()

print("Best checkpoint loaded successfully!")
print("Checkpoint epoch:", checkpoint["epoch"])
print("Validation loss:", round(checkpoint["val_loss"], 4))
print("Validation ROC-AUC:", round(checkpoint["val_auc"], 4))
print("Evaluation device:", device)

Best checkpoint loaded successfully!
Checkpoint epoch: 6
Validation loss: 0.6787
Validation ROC-AUC: 0.6712
Evaluation device: cuda

In [81]:
import numpy as np
import pandas as pd
import torch

from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    roc_auc_score,
    average_precision_score,
    confusion_matrix,
    classification_report
)

model.eval()

test_labels = []
test_probs = []

print(f"Evaluating {len(test_genome_ids)} test genomes...")

with torch.no_grad():
    for i, genome_id in enumerate(test_genome_ids, start=1):

        genome_embedding, attention_weights, logit, label = forward_genome(
            model,
            genome_id,
            batch_size=WINDOW_BATCH_SIZE,
            device=device
        )

        probability = torch.sigmoid(logit).item()

        test_labels.append(int(label))
        test_probs.append(probability)

        del genome_embedding, attention_weights, logit

        if i % 10 == 0 or i == len(test_genome_ids):
            print(f"Evaluated {i}/{len(test_genome_ids)} genomes")

y_true = np.array(test_labels)
y_probs = np.array(test_probs)
y_pred = (y_probs >= 0.5).astype(int)

print("\nTEST SET RESULTS")
print("=" * 45)
print("Accuracy:", round(accuracy_score(y_true, y_pred), 4))
print("Precision:", round(precision_score(y_true, y_pred, zero_division=0), 4))
print("Recall:", round(recall_score(y_true, y_pred, zero_division=0), 4))
print("F1-score:", round(f1_score(y_true, y_pred, zero_division=0), 4))
print("ROC-AUC:", round(roc_auc_score(y_true, y_probs), 4))
print("PR-AUC (average precision):", round(average_precision_score(y_true, y_probs), 4))

print("\nConfusion matrix:")
print(confusion_matrix(y_true, y_pred))

print("\nClassification report:")
print(classification_report(
    y_true,
    y_pred,
    target_names=["Susceptible (0)", "Resistant (1)"],
    zero_division=0
))

Evaluating 171 test genomes...
Evaluated 10/171 genomes
Evaluated 20/171 genomes
Evaluated 30/171 genomes
Evaluated 40/171 genomes
Evaluated 50/171 genomes
Evaluated 60/171 genomes
Evaluated 70/171 genomes
Evaluated 80/171 genomes
Evaluated 90/171 genomes
Evaluated 100/171 genomes
Evaluated 110/171 genomes
Evaluated 120/171 genomes
Evaluated 130/171 genomes
Evaluated 140/171 genomes
Evaluated 150/171 genomes
Evaluated 160/171 genomes
Evaluated 170/171 genomes
Evaluated 171/171 genomes

TEST SET RESULTS
=============================================
Accuracy: 0.5848
Precision: 0.0
Recall: 0.0
F1-score: 0.0
ROC-AUC: 0.6246
PR-AUC (average precision): 0.5195

Confusion matrix:
[[100   0]
 [ 71   0]]

Classification report:
                 precision    recall  f1-score   support

Susceptible (0)       0.58      1.00      0.74       100
  Resistant (1)       0.00      0.00      0.00        71

       accuracy                           0.58       171
      macro avg       0.29      0.50      0.37       171
   weighted avg       0.34      0.58      0.43       171

In [82]:
import numpy as np
import pandas as pd

# Inspect the variables produced by the test evaluation
required = ["y_true", "y_probs"]

for name in required:
    print(f"{name} available:", name in globals())

if all(name in globals() for name in required):
    y_true_arr = np.asarray(y_true).astype(int).ravel()
    y_probs_arr = np.asarray(y_probs).astype(float).ravel()

    print("\nNumber of test genomes:", len(y_true_arr))
    print("Actual labels:", np.unique(y_true_arr, return_counts=True))
    print("\nProbability summary:")
    print(pd.Series(y_probs_arr).describe())

    print("\nProbabilities by actual class:")
    results = pd.DataFrame({
        "actual_label": y_true_arr,
        "resistance_probability": y_probs_arr
    })

    print(
        results.groupby("actual_label")["resistance_probability"]
        .agg(["count", "mean", "std", "min", "median", "max"])
        .rename(index={0: "Susceptible", 1: "Resistant"})
    )

    print("\nPredictions at different thresholds:")
    for threshold in [0.3, 0.4, 0.5, 0.6, 0.7]:
        predicted = (y_probs_arr >= threshold).astype(int)
        print(
            f"Threshold {threshold:.1f}: "
            f"{predicted.sum()} genomes predicted resistant"
        )
else:
    print(
        "\nThose variable names are unavailable. "
        "We'll inspect the evaluation cell to identify the correct names."
    )

y_true available: True
y_probs available: True

Number of test genomes: 171
Actual labels: (array([0, 1]), array([100,  71]))

Probability summary:
count    171.000000
mean       0.411763
std        0.000007
min        0.411743
25%        0.411757
50%        0.411762
75%        0.411768
max        0.411778
dtype: float64

Probabilities by actual class:
              count      mean       std       min    median       max
actual_label
Susceptible     100  0.411762  0.000007  0.411743  0.411761  0.411778
Resistant        71  0.411765  0.000007  0.411748  0.411765  0.411777

Predictions at different thresholds:
Threshold 0.3: 171 genomes predicted resistant
Threshold 0.4: 171 genomes predicted resistant
Threshold 0.5: 0 genomes predicted resistant
Threshold 0.6: 0 genomes predicted resistant
Threshold 0.7: 0 genomes predicted resistant

In [83]:
import torch

model.eval()

print("Model architecture:\n")
print(model)

print("\nFinal classifier parameters:")
for name, param in model.named_parameters():
    if any(key in name.lower() for key in ["classifier", "attention", "fc", "output"]):
        print(
            name,
            "| shape:", tuple(param.shape),
            "| mean:", round(param.detach().float().mean().item(), 6),
            "| std:", round(param.detach().float().std().item(), 6)
        )

Model architecture:

GenomeAMRModel(
  (cnn): GenomeCNN(
    (conv1): Conv1d(4, 64, kernel_size=(15,), stride=(1,), padding=(7,))
    (conv2): Conv1d(64, 128, kernel_size=(15,), stride=(1,), padding=(7,))
    (relu): ReLU()
    (pool): MaxPool1d(kernel_size=2, stride=2, padding=0, dilation=1, ceil_mode=False)
    (global_pool): AdaptiveMaxPool1d(output_size=1)
    (embedding): Linear(in_features=128, out_features=128, bias=True)
  )
  (mil): AttentionMIL(
    (attention): Sequential(
      (0): Linear(in_features=128, out_features=64, bias=True)
      (1): Tanh()
      (2): Linear(in_features=64, out_features=1, bias=True)
    )
    (classifier): Linear(in_features=128, out_features=1, bias=True)
  )
)

Final classifier parameters:
mil.attention.0.weight | shape: (64, 128) | mean: -0.000153 | std: 0.094413
mil.attention.0.bias | shape: (64,) | mean: -0.015613 | std: 0.092581
mil.attention.2.weight | shape: (1, 64) | mean: -0.008695 | std: 0.036751
mil.attention.2.bias | shape: (1,) | mean: -0.089246 | std: nan
mil.classifier.weight | shape: (1, 128) | mean: -0.00116 | std: 0.036747
mil.classifier.bias | shape: (1,) | mean: -0.055137 | std: nan

/tmp/ipykernel_49/154052963.py:15: UserWarning: std(): degrees of freedom is <= 0. Correction should be strictly less than the reduction factor (input numel divided by output numel). (Triggered internally at /pytorch/aten/src/ATen/native/ReduceOps.cpp:1858.)
  "| std:", round(param.detach().float().std().item(), 6)

In [84]:
import torch

# Check for NaN or infinite model parameters
bad_parameters = []

for name, param in model.named_parameters():
    if not torch.isfinite(param).all():
        bad_parameters.append(name)

print("Non-finite parameter tensors:", bad_parameters)
print("All model parameters finite:", len(bad_parameters) == 0)

Non-finite parameter tensors: []
All model parameters finite: True

In [85]:
# Compare CNN embeddings from two different test genomes
model.eval()

genome_a = test_genome_ids[0]
genome_b = test_genome_ids[1]

with torch.no_grad():
    embedding_a, attention_a, logit_a, label_a = forward_genome(
        model, genome_a, batch_size=WINDOW_BATCH_SIZE, device=device
    )

    embedding_b, attention_b, logit_b, label_b = forward_genome(
        model, genome_b, batch_size=WINDOW_BATCH_SIZE, device=device
    )

print("Genome A:", genome_a)
print("Genome B:", genome_b)

print("\nEmbedding A — standard deviation:",
      embedding_a.float().std().item())
print("Embedding B — standard deviation:",
      embedding_b.float().std().item())

print("\nMean absolute difference between embeddings:",
      (embedding_a.float() - embedding_b.float()).abs().mean().item())

print("\nLogit A:", logit_a.item())
print("Logit B:", logit_b.item())

Genome A: 1280.51882
Genome B: 1280.59374

Embedding A — standard deviation: 0.0676109790802002
Embedding B — standard deviation: 0.06760725378990173

Mean absolute difference between embeddings: 1.237905235029757e-05

Logit A: -0.3566935062408447
Logit B: -0.356681227684021

In [87]:
import inspect

for name, obj in globals().copy().items():
    if callable(obj) and (
        "window" in name.lower()
        or "fasta" in name.lower()
        or "genome" in name.lower()
        or "encode" in name.lower()
    ):
        try:
            print(f"{name}{inspect.signature(obj)}")
        except (TypeError, ValueError):
            print(name)

parse_fasta(fasta_path)
generate_windows(sequence, window_size=500, stride=250)
estimate_split_windows(split_df)
process_genome(genome_id)
one_hot_encode(sequence)
generate_window_batches(windows, batch_size=128)
GenomeCNN()
GenomeAMRModel()
generate_genome_training_batches(genome_id, batch_size=128)
forward_genome(model, genome_id, batch_size=128, device='cpu')

In [88]:
import torch

model.eval()

# Select two different genomes from your test set
genome_a = test_genome_ids[0]
genome_b = test_genome_ids[1]

# Parse their FASTA sequences
contigs_a = parse_fasta(genome_dir / f"{genome_a}.fna")
contigs_b = parse_fasta(genome_dir / f"{genome_b}.fna")

print("Genome A:", genome_a)
print("Genome B:", genome_b)
print("Contigs A:", len(contigs_a))
print("Contigs B:", len(contigs_b))

Genome A: 1280.51882
Genome B: 1280.59374
Contigs A: 76
Contigs B: 43

In [89]:
import torch
import numpy as np

model.eval()

# Get the first contig sequence from each genome
seq_a = next(iter(contigs_a.values())) if isinstance(contigs_a, dict) else contigs_a[0][1]
seq_b = next(iter(contigs_b.values())) if isinstance(contigs_b, dict) else contigs_b[0][1]

# Generate 500 bp windows
windows_a = generate_windows(seq_a, window_size=500, stride=250)
windows_b = generate_windows(seq_b, window_size=500, stride=250)

print("Windows from Genome A's first contig:", len(windows_a))
print("Windows from Genome B's first contig:", len(windows_b))

Windows from Genome A's first contig: 336
Windows from Genome B's first contig: 165

In [92]:
print("Type of contigs_a:", type(contigs_a))
print("Type of first item in contigs_a:", type(next(iter(contigs_a.values()))))

first_item = next(iter(contigs_a.values()))

if isinstance(first_item, dict):
    print("Keys inside first contig item:", list(first_item.keys())[:10])
elif isinstance(first_item, str):
    print("First DNA sequence preview:", first_item[:80])
else:
    print("First item preview:", repr(first_item)[:200])

Type of contigs_a: <class 'dict'>
Type of first item in contigs_a: <class 'str'>
First DNA sequence preview: GAAAATAATCTCTTCAATTTATTTTTATATGAATCCTGTGACTCAATGATTGTAATATCTAAAGATTTCAGTTCATCATA

In [95]:
# Compare CNN features from two different genomes
import numpy as np
import torch

def get_cnn_features(contigs):
    # Select one DNA sequence from the genome
    sequences = list(contigs.values())
    selected = [sequences[0], sequences[min(1, len(sequences) - 1)]]

    # Encode the selected sequences
   # Use equal-length 500 bp windows from each contig
    selected_windows = [seq[:500] for seq in selected if len(seq) >= 500]
    batch = np.stack([one_hot_encode(seq) for seq in selected_windows])
    x = torch.tensor(batch, dtype=torch.float32, device=device)

    model.eval()
    with torch.no_grad():
        features = model.cnn(x)

    return features.detach().cpu().numpy()

features_a = get_cnn_features(contigs_a)
features_b = get_cnn_features(contigs_b)

print("Genome A CNN features:", features_a.shape)
print("Genome B CNN features:", features_b.shape)
print("Mean absolute CNN feature difference:",
      float(np.abs(features_a.mean(axis=0) - features_b.mean(axis=0)).mean()))

Genome A CNN features: (2, 128)
Genome B CNN features: (2, 128)
Mean absolute CNN feature difference: 0.0007439024047926068

In [96]:
# Compare the CNN features before and after training?
# First, inspect the trained CNN's activation scale.

import torch

model.eval()

with torch.no_grad():
    print("CNN parameter summary:")
    for name, param in model.cnn.named_parameters():
        print(
            f"{name}: mean={param.mean().item():.6f}, "
            f"std={param.std().item():.6f}"
        )

print("\nSampled contig lengths:")
print("Genome A:", [len(seq) for seq in list(contigs_a.values())[:5]])
print("Genome B:", [len(seq) for seq in list(contigs_b.values())[:5]])

CNN parameter summary:
conv1.weight: mean=-0.053365, std=0.072473
conv1.bias: mean=-0.057694, std=0.073536
conv2.weight: mean=-0.009814, std=0.019957
conv2.bias: mean=-0.027448, std=0.017554
embedding.weight: mean=-0.000051, std=0.052762
embedding.bias: mean=0.001839, std=0.065529

Sampled contig lengths:
Genome A: [84417, 71050, 8449, 1918, 38366]
Genome B: [41660, 27242, 102545, 38842, 17912]

In [97]:
import pandas as pd
from pathlib import Path

# Inspect the recorded training history, if it is still in memory
if "history" in globals() and history:
    history_df = pd.DataFrame(history)
    display(history_df)
else:
    print("Training history is not available in memory.")

# Inspect checkpoint metadata
checkpoint = torch.load(
    Path("models") / "best_amr_genome_cnn.pt",
    map_location=device,
    weights_only=False
)

print("Best checkpoint epoch:", checkpoint["epoch"])
print("Training loss:", checkpoint.get("train_loss"))
print("Validation loss:", checkpoint.get("val_loss"))
print("Validation accuracy:", checkpoint.get("val_accuracy"))
print("Validation ROC-AUC:", checkpoint.get("val_auc"))

   epoch  train_loss  val_loss  val_accuracy   val_auc
0      1    0.685776  0.679562      0.584795  0.682887
1      2    0.682257  0.678730      0.584795  0.788521
2      3    0.682012  0.679635      0.584795  0.802606
3      4    0.691991  0.678764      0.584795  0.662676
4      5    0.681978  0.678748      0.584795  0.665141
5      6    0.680994  0.678717      0.584795  0.671197
6      7    0.681034  0.678920      0.584795  0.687183
7      8    0.680876  0.678787      0.584795  0.707958
8      9    0.680851  0.678913      0.584795  0.721549
9     10    0.680338  0.679441      0.584795  0.727113

Best checkpoint epoch: 6
Training loss: 0.6809944755692577
Validation loss: 0.678717163222575
Validation accuracy: 0.5847953216374269
Validation ROC-AUC: 0.6711971830985916

In [98]:
print("Best epoch:", checkpoint["epoch"])
print("Best validation ROC-AUC:", checkpoint["val_auc"])

# Check how many distinct predictions the model makes
model.load_state_dict(checkpoint["model_state_dict"])
model.eval()

print("\nModel restored from best checkpoint.")
print("CNN device:", next(model.cnn.parameters()).device)
print("MIL device:", next(model.mil.parameters()).device)

Best epoch: 6
Best validation ROC-AUC: 0.6711971830985916

Model restored from best checkpoint.
CNN device: cuda:0
MIL device: cuda:0