In [1]:
import pandas as pd
import numpy as np
from pathlib import Path

print("Everything imported successfully!")

Everything imported successfully!

In [2]:
PROJECT_ROOT = Path.cwd().parent

RAW_DATA = PROJECT_ROOT / "data" / "raw" / "S.aureus_ciprofloxacin_broth_dilution.xlsx"
PROCESSED_DATA = PROJECT_ROOT / "data" / "processed"

print("Project root:", PROJECT_ROOT)
print("Raw data:", RAW_DATA)
print("Processed data:", PROCESSED_DATA)

Project root: d:\4th Year 7th Sem\AI and Systems Biology in Precision Medicine\AMR_Genome_CNN
Raw data: d:\4th Year 7th Sem\AI and Systems Biology in Precision Medicine\AMR_Genome_CNN\data\raw\S.aureus_ciprofloxacin_broth_dilution.xlsx
Processed data: d:\4th Year 7th Sem\AI and Systems Biology in Precision Medicine\AMR_Genome_CNN\data\processed

In [3]:
df = pd.read_excel(RAW_DATA)

print("Dataset shape:", df.shape)

Dataset shape: (1347, 21)

## **Verified dataset structure**  
   The raw dataset contains 1,347 records and 21 columns.

In [4]:
df.head()

,Taxon ID,Genome ID,Genome Name,Antibiotic,Resistant Phenotype,Measurement,Measurement Sign,Measurement Value,Measurement Unit,Laboratory Typing Method,...,Laboratory Typing Platform,Vendor,Testing Standard,Testing Standard Year,Computational Method,Computational Method Version,Computational Method Performance,Evidence,Source,PubMed
0,1280,1280.59625,Staphylococcus aureus CFSA17SA032,ciprofloxacin,Susceptible,NaN,NaN,NaN,NaN,Biofosun Gram-positive panels broth dilution,...,NaN,"Shanghai Biofosun Biotech, China",CLSI,2015.0,NaN,NaN,NaN,Laboratory Method,NaN,34100643.0
1,1280,1280.15875,Staphylococcus aureus strain HCW05_100415,ciprofloxacin,NaN,<=0.5,<=,0.5,mg/L,Broth dilution,...,NaN,BioMerieux,EUCAST,NaN,NaN,NaN,NaN,Laboratory Method,NaN,28704546.0
2,1280,1280.51785,Staphylococcus aureus 09-02538,ciprofloxacin,Resistant,NaN,NaN,NaN,NaN,Broth dilution,...,NaN,NaN,EUCAST,2018.0,NaN,NaN,NaN,Laboratory Method,NaN,33658988.0
3,1280,1280.51770,Staphylococcus aureus 14-02100,ciprofloxacin,Susceptible,NaN,NaN,NaN,NaN,Broth dilution,...,NaN,NaN,EUCAST,2018.0,NaN,NaN,NaN,Laboratory Method,NaN,33658988.0
4,1280,1280.59567,Staphylococcus aureus CFSA17SA094,ciprofloxacin,Susceptible,NaN,NaN,NaN,NaN,Biofosun Gram-positive panels broth dilution,...,NaN,"Shanghai Biofosun Biotech, China",CLSI,2015.0,NaN,NaN,NaN,Laboratory Method,NaN,34100643.0

In [5]:
print("Columns:")
for i, column in enumerate(df.columns, start=1):
    print(f"{i}. {column}")

Columns:
1. Taxon ID
2. Genome ID
3. Genome Name
4. Antibiotic
5. Resistant Phenotype
6. Measurement
7. Measurement Sign
8. Measurement Value
9. Measurement Unit
10. Laboratory Typing Method
11. Laboratory Typing Method Version
12. Laboratory Typing Platform
13. Vendor
14. Testing Standard
15. Testing Standard Year
16. Computational Method
17. Computational Method Version
18. Computational Method Performance
19. Evidence
20. Source
21. PubMed

In [6]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1347 entries, 0 to 1346
Data columns (total 21 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   Taxon ID                          1347 non-null   int64
 1   Genome ID                         1347 non-null   float64
 2   Genome Name                       1347 non-null   str
 3   Antibiotic                        1347 non-null   str
 4   Resistant Phenotype               1260 non-null   str
 5   Measurement                       201 non-null    str
 6   Measurement Sign                  177 non-null    str
 7   Measurement Value                 201 non-null    float64
 8   Measurement Unit                  201 non-null    str
 9   Laboratory Typing Method          1347 non-null   str
 10  Laboratory Typing Method Version  0 non-null      float64
 11  Laboratory Typing Platform        412 non-null    str
 12  Vendor                            1163 non-null   str
 13  Testing Standard                  1347 non-null   str
 14  Testing Standard Year             970 non-null    float64
 15  Computational Method              0 non-null      float64
 16  Computational Method Version      0 non-null      float64
 17  Computational Method Performance  0 non-null      float64
 18  Evidence                          1347 non-null   str
 19  Source                            0 non-null      float64
 20  PubMed                            1332 non-null   float64
dtypes: float64(9), int64(1), str(11)
memory usage: 221.1 KB

In [7]:
print("Total records:", len(df))
print("Total columns:", len(df.columns))

Total records: 1347
Total columns: 21

## **Verified antibiotic identity**  
   All 1,347 records correspond to ciprofloxacin, so no additional antibiotic filtering is required.

In [8]:
print("\nAntibiotic distribution:")
print(df["Antibiotic"].value_counts(dropna=False))

Antibiotic distribution:
Antibiotic
ciprofloxacin    1347
Name: count, dtype: int64

## **Inspected phenotype distribution**  
   The dataset contains 691 Susceptible, 516 Resistant, 53 Intermediate, and 87 records with missing phenotype values.

In [9]:
print("\nPhenotype distribution:")
print(df["Resistant Phenotype"].value_counts(dropna=False))

Phenotype distribution:
Resistant Phenotype
Susceptible     691
Resistant       516
NaN              87
Intermediate     53
Name: count, dtype: int64

## Check Genome IDs

In [10]:
print("Total records:", len(df))
print("Unique Genome IDs:", df["Genome ID"].nunique())
print("Missing Genome IDs:", df["Genome ID"].isna().sum())

Total records: 1347
Unique Genome IDs: 1281
Missing Genome IDs: 0

In [11]:
print("Duplicate Genome ID records:",
      df["Genome ID"].duplicated().sum())

Duplicate Genome ID records: 66

In [12]:
print(df["Genome ID"].head(10).tolist())

[1280.59625, 1280.15875, 1280.51785, 1280.5177, 1280.59567, 1280.51748, 1280.59662, 1280.9387, 1280.15898, 1280.59517]

## Step 5 — Check the duplicate genomes

In [13]:
duplicate_genomes = (
    df[df["Genome ID"].duplicated(keep=False)]
    .sort_values("Genome ID")
)

print("Records belonging to duplicated Genome IDs:",
      len(duplicate_genomes))

print("Number of duplicated Genome IDs:",
      duplicate_genomes["Genome ID"].nunique())

Records belonging to duplicated Genome IDs: 132
Number of duplicated Genome IDs: 66

In [14]:
duplicate_genomes

,Taxon ID,Genome ID,Genome Name,Antibiotic,Resistant Phenotype,Measurement,Measurement Sign,Measurement Value,Measurement Unit,Laboratory Typing Method,...,Laboratory Typing Platform,Vendor,Testing Standard,Testing Standard Year,Computational Method,Computational Method Version,Computational Method Performance,Evidence,Source,PubMed
1251,1280,1280.15865,Staphylococcus aureus strain N32_250215,ciprofloxacin,NaN,<=0.5,<=,0.5,mg/L,Broth dilution,...,NaN,BioMerieux,EUCAST,NaN,NaN,NaN,NaN,Laboratory Method,NaN,28704546.0
1159,1280,1280.15865,Staphylococcus aureus strain N32_250215,ciprofloxacin,Susceptible,NaN,NaN,NaN,NaN,Broth dilution,...,VITEK 2,BioMerieux,EUCAST,NaN,NaN,NaN,NaN,Laboratory Method,NaN,28704546.0
259,1280,1280.15866,Staphylococcus aureus strain HCW11A_151214,ciprofloxacin,NaN,<=0.5,<=,0.5,mg/L,Broth dilution,...,NaN,BioMerieux,EUCAST,NaN,NaN,NaN,NaN,Laboratory Method,NaN,28704546.0
1082,1280,1280.15866,Staphylococcus aureus strain HCW11A_151214,ciprofloxacin,Susceptible,NaN,NaN,NaN,NaN,Broth dilution,...,VITEK 2,BioMerieux,EUCAST,NaN,NaN,NaN,NaN,Laboratory Method,NaN,28704546.0
753,1280,1280.15867,Staphylococcus aureus strain N36_040315,ciprofloxacin,NaN,<=0.5,<=,0.5,mg/L,Broth dilution,...,NaN,BioMerieux,EUCAST,NaN,NaN,NaN,NaN,Laboratory Method,NaN,28704546.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1073,1280,1280.15929,Staphylococcus aureus strain HCW21A_160215,ciprofloxacin,NaN,<=0.5,<=,0.5,mg/L,Broth dilution,...,NaN,BioMerieux,EUCAST,NaN,NaN,NaN,NaN,Laboratory Method,NaN,28704546.0
1061,1280,1280.15930,Staphylococcus aureus strain 13C,ciprofloxacin,Resistant,>2,>,2.0,mg/L,Broth dilution,...,MicroScan,Siemens,CLSI,NaN,NaN,NaN,NaN,Laboratory Method,NaN,NaN
1158,1280,1280.15930,Staphylococcus aureus strain 13C,ciprofloxacin,Resistant,>=8,>=,8.0,mg/L,Broth dilution,...,VITEK 2,BioMerieux,CLSI,NaN,NaN,NaN,NaN,Laboratory Method,NaN,NaN
776,1280,1280.15931,Staphylococcus aureus strain LAC,ciprofloxacin,Resistant,>=8,>=,8.0,mg/L,Broth dilution,...,VITEK 2,BioMerieux,CLSI,NaN,NaN,NaN,NaN,Laboratory Method,NaN,NaN
712,1280,1280.15931,Staphylococcus aureus strain LAC,ciprofloxacin,Resistant,>2,>,2.0,mg/L,Broth dilution,...,MicroScan,Siemens,CLSI,NaN,NaN,NaN,NaN,Laboratory Method,NaN,NaN

## Step 6 — Check for phenotype conflicts

In [15]:
phenotype_by_genome = (
    df.groupby("Genome ID")["Resistant Phenotype"]
      .apply(lambda x: set(x.dropna()))
)

conflicting_genomes = phenotype_by_genome[
    phenotype_by_genome.apply(
        lambda x: "Resistant" in x and "Susceptible" in x
    )
]

print("Genomes with Resistant/Susceptible conflicts:",
      len(conflicting_genomes))

Genomes with Resistant/Susceptible conflicts: 0

## Step 7 — Investigate duplicate Genome IDs
🧬 Cell 7.1 — Summarize every duplicated genome

In [16]:
duplicate_summary = (
    df[df["Genome ID"].duplicated(keep=False)]
    .groupby("Genome ID")
    .agg(
        records=("Genome ID", "size"),
        phenotypes=("Resistant Phenotype", lambda x: set(x.dropna())),
        measurements=("Measurement", lambda x: list(x.dropna())),
        measurement_units=("Measurement Unit", lambda x: set(x.dropna())),
    )
    .sort_index()
)

duplicate_summary.head(20)

            records     phenotypes measurements measurement_units
Genome ID
1280.15865        2  {Susceptible}      [<=0.5]            {mg/L}
1280.15866        2  {Susceptible}      [<=0.5]            {mg/L}
1280.15867        2  {Susceptible}      [<=0.5]            {mg/L}
1280.15868        2  {Susceptible}      [<=0.5]            {mg/L}
1280.15869        2  {Susceptible}      [<=0.5]            {mg/L}
1280.15870        2  {Susceptible}      [<=0.5]            {mg/L}
1280.15871        2  {Susceptible}      [<=0.5]            {mg/L}
1280.15872        2  {Susceptible}      [<=0.5]            {mg/L}
1280.15873        2  {Susceptible}      [<=0.5]            {mg/L}
1280.15874        2  {Susceptible}      [<=0.5]            {mg/L}
1280.15875        2  {Susceptible}      [<=0.5]            {mg/L}
1280.15876        2  {Susceptible}      [<=0.5]            {mg/L}
1280.15877        2  {Susceptible}      [<=0.5]            {mg/L}
1280.15878        2  {Susceptible}      [<=0.5]            {mg/L}
1280.15880        2    {Resistant}        [>=8]            {mg/L}
1280.15881        2    {Resistant}        [>=8]            {mg/L}
1280.15882        2    {Resistant}        [>=8]            {mg/L}
1280.15883        2  {Susceptible}      [<=0.5]            {mg/L}
1280.15884        2    {Resistant}        [>=8]            {mg/L}
1280.15885        2    {Resistant}        [>=8]            {mg/L}

## Step 7.2 — See how many records each duplicated genome has

In [17]:
print("Distribution of records per duplicated Genome ID:")
print(duplicate_summary["records"].value_counts().sort_index())

Distribution of records per duplicated Genome ID:
records
2    66
Name: count, dtype: int64

## Step 7.3 — Check phenotype patterns

In [18]:
phenotype_patterns = (
    df.groupby("Genome ID")["Resistant Phenotype"]
    .agg(lambda x: tuple(sorted(set(x.dropna()))))
)

print("Phenotype patterns across all genomes:")
print(phenotype_patterns.value_counts())

Phenotype patterns across all genomes:
Resistant Phenotype
(Susceptible,)     691
(Resistant,)       514
(Intermediate,)     53
()                  23
Name: count, dtype: int64

## Step 7.4 — Find genomes with no phenotype

In [19]:
missing_phenotype_genomes = phenotype_patterns[
    phenotype_patterns == ()
]

print("Genomes with no phenotype:", len(missing_phenotype_genomes))

Genomes with no phenotype: 23

## Step 8 — Define the binary classification cohort

For the CNN, the prediction task is binary classification of ciprofloxacin resistance.

Therefore:
- Resistant → retained as class 1
- Susceptible → retained as class 0
- Intermediate → excluded because it does not belong to either binary class
- Missing phenotype → excluded because no training label is available

In [20]:
print("Usable binary genomes:")

binary_genomes = phenotype_patterns[
    phenotype_patterns.isin([
        ("Resistant",),
        ("Susceptible",)
    ])
]

print("Total:", len(binary_genomes))
print("\nClass distribution:")
print(binary_genomes.value_counts())

Usable binary genomes:
Total: 1205

Class distribution:
Resistant Phenotype
(Susceptible,)    691
(Resistant,)      514
Name: count, dtype: int64

## Step 9 — Create one record per genome

Each genome must appear exactly once in the final binary dataset.

The phenotype is encoded as:
- 0 = Susceptible
- 1 = Resistant

Intermediate and missing-phenotype genomes are excluded from the binary classification cohort.

In [24]:
# Create one row per genome using the verified phenotype patterns

clean_genomes = pd.DataFrame({
    "Genome ID": binary_genomes.index,
    "Phenotype": binary_genomes.values
})

# Convert phenotype tuples to binary labels

clean_genomes["Label"] = clean_genomes["Phenotype"].map({
    ("Susceptible",): 0,
    ("Resistant",): 1
})

clean_genomes = clean_genomes.sort_values("Genome ID").reset_index(drop=True)

print("Clean genome-level dataset:")
print("Total genomes:", len(clean_genomes))

print("\nLabel distribution:")
print(clean_genomes["Label"].value_counts().sort_index())

Clean genome-level dataset:
Total genomes: 1205

Label distribution:
Label
0    691
1    514
Name: count, dtype: int64

In [25]:
print("Unique Genome IDs:", clean_genomes["Genome ID"].nunique())
print("Duplicate Genome IDs:", clean_genomes["Genome ID"].duplicated().sum())

print("\nFirst 10 genomes:")
print(clean_genomes.head(10))

Unique Genome IDs: 1205
Duplicate Genome IDs: 0

First 10 genomes:
    Genome ID       Phenotype  Label
0  1280.15865  (Susceptible,)      0
1  1280.15866  (Susceptible,)      0
2  1280.15867  (Susceptible,)      0
3  1280.15868  (Susceptible,)      0
4  1280.15869  (Susceptible,)      0
5  1280.15870  (Susceptible,)      0
6  1280.15871  (Susceptible,)      0
7  1280.15872  (Susceptible,)      0
8  1280.15873  (Susceptible,)      0
9  1280.15874  (Susceptible,)      0

## Step 10 — Save the clean genome-level dataset

The cleaned genome-level dataset is saved separately from the raw data so that the original dataset remains unchanged and the preprocessing step is reproducible.

In [26]:
# Save the cleaned genome-level dataset

output_path = "../data/processed/ciprofloxacin_genome_level.csv"

clean_genomes.to_csv(output_path, index=False)

print("Clean dataset saved to:", output_path)
print("Rows saved:", len(clean_genomes))

Clean dataset saved to: ../data/processed/ciprofloxacin_genome_level.csv
Rows saved: 1205

## Step 11 — Verify the saved dataset

Reload the processed dataset from disk and verify its dimensions, labels, and Genome ID uniqueness.

In [27]:
# Reload the saved dataset

verified_genomes = pd.read_csv(
    "../data/processed/ciprofloxacin_genome_level.csv"
)

print("Shape:", verified_genomes.shape)
print("Unique Genome IDs:", verified_genomes["Genome ID"].nunique())
print("Duplicate Genome IDs:", verified_genomes["Genome ID"].duplicated().sum())

print("\nLabel distribution:")
print(verified_genomes["Label"].value_counts().sort_index())

print("\nFirst 5 rows:")
print(verified_genomes.head())

Shape: (1205, 3)
Unique Genome IDs: 1205
Duplicate Genome IDs: 0

Label distribution:
Label
0    691
1    514
Name: count, dtype: int64

First 5 rows:
    Genome ID         Phenotype  Label
0  1280.15865  ('Susceptible',)      0
1  1280.15866  ('Susceptible',)      0
2  1280.15867  ('Susceptible',)      0
3  1280.15868  ('Susceptible',)      0
4  1280.15869  ('Susceptible',)      0

## Step 12 — Inspect genome identifiers

The cleaned dataset contains unique Genome IDs that will be used to link antimicrobial-resistance phenotypes with their corresponding genome sequences.

In [28]:
# Inspect genome identifiers

print("Number of genomes:", len(verified_genomes))

print("\nFirst 20 Genome IDs:")
print(verified_genomes["Genome ID"].head(20).tolist())

print("\nLast 20 Genome IDs:")
print(verified_genomes["Genome ID"].tail(20).tolist())

Number of genomes: 1205

First 20 Genome IDs:
[1280.15865, 1280.15866, 1280.15867, 1280.15868, 1280.15869, 1280.1587, 1280.15871, 1280.15872, 1280.15873, 1280.15874, 1280.15875, 1280.15876, 1280.15877, 1280.15878, 1280.1588, 1280.15881, 1280.15882, 1280.15883, 1280.15884, 1280.15885]

Last 20 Genome IDs:
[1280.9378, 1280.9379, 1280.938, 1280.9381, 1280.9382, 1280.9383, 1280.9384, 1280.9385, 1280.9386, 1280.9388, 1280.9398, 1280.9399, 1280.94, 1280.9401, 1280.9402, 1280.9403, 1280.9404, 1280.9405, 1280.9406, 1280.9407]